/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BillingUnit from './model/BillingUnit';
import BillingUnitRequest from './model/BillingUnitRequest';
import CapabilityStatement from './model/CapabilityStatement';
import CapabilityStatementRequest from './model/CapabilityStatementRequest';
import Client from './model/Client';
import ClientRequest from './model/ClientRequest';
import ContactMessage from './model/ContactMessage';
import ContactMessageRequest from './model/ContactMessageRequest';
import Employee from './model/Employee';
import EmployeeRequest from './model/EmployeeRequest';
import Expertise from './model/Expertise';
import FeatureSection from './model/FeatureSection';
import Image from './model/Image';
import LeaveEntry from './model/LeaveEntry';
import LeaveEntryRequest from './model/LeaveEntryRequest';
import LeaveTypeEnum from './model/LeaveTypeEnum';
import LegalSection from './model/LegalSection';
import LegalSectionRequest from './model/LegalSectionRequest';
import LocationOffice from './model/LocationOffice';
import LocationSection from './model/LocationSection';
import LocationSectionRequest from './model/LocationSectionRequest';
import Operation from './model/Operation';
import OperationRequest from './model/OperationRequest';
import OperationStatusEnum from './model/OperationStatusEnum';
import OrganisationLogos from './model/OrganisationLogos';
import OrganisationSection from './model/OrganisationSection';
import OrganisationSectionRequest from './model/OrganisationSectionRequest';
import PaginatedBillingUnitList from './model/PaginatedBillingUnitList';
import PaginatedCapabilityStatementList from './model/PaginatedCapabilityStatementList';
import PaginatedClientList from './model/PaginatedClientList';
import PaginatedEmployeeList from './model/PaginatedEmployeeList';
import PaginatedExpertiseList from './model/PaginatedExpertiseList';
import PaginatedFeatureSectionList from './model/PaginatedFeatureSectionList';
import PaginatedLeaveEntryList from './model/PaginatedLeaveEntryList';
import PaginatedLocationOfficeList from './model/PaginatedLocationOfficeList';
import PaginatedOperationList from './model/PaginatedOperationList';
import PaginatedOrganisationLogosList from './model/PaginatedOrganisationLogosList';
import PaginatedOrganisationSectionList from './model/PaginatedOrganisationSectionList';
import PaginatedQuickNoteList from './model/PaginatedQuickNoteList';
import PaginatedRegionList from './model/PaginatedRegionList';
import PaginatedSectionList from './model/PaginatedSectionList';
import PaginatedSocialMediaList from './model/PaginatedSocialMediaList';
import PaginatedTaskList from './model/PaginatedTaskList';
import PaginatedTimesheetEntryList from './model/PaginatedTimesheetEntryList';
import PaginatedTimesheetSubmissionList from './model/PaginatedTimesheetSubmissionList';
import PaginatedValueList from './model/PaginatedValueList';
import PaginatedValueStatementList from './model/PaginatedValueStatementList';
import PaginatedWorkOrderList from './model/PaginatedWorkOrderList';
import PatchedBillingUnitRequest from './model/PatchedBillingUnitRequest';
import PatchedCapabilityStatementRequest from './model/PatchedCapabilityStatementRequest';
import PatchedClientRequest from './model/PatchedClientRequest';
import PatchedEmployeeRequest from './model/PatchedEmployeeRequest';
import PatchedLeaveEntryRequest from './model/PatchedLeaveEntryRequest';
import PatchedLegalSectionRequest from './model/PatchedLegalSectionRequest';
import PatchedLocationSectionRequest from './model/PatchedLocationSectionRequest';
import PatchedOperationRequest from './model/PatchedOperationRequest';
import PatchedOrganisationSectionRequest from './model/PatchedOrganisationSectionRequest';
import PatchedQuickNoteRequest from './model/PatchedQuickNoteRequest';
import PatchedRegionRequest from './model/PatchedRegionRequest';
import PatchedSocialMediaRequest from './model/PatchedSocialMediaRequest';
import PatchedTaskRequest from './model/PatchedTaskRequest';
import PatchedTimesheetEntryRequest from './model/PatchedTimesheetEntryRequest';
import PatchedTimesheetSubmissionRequest from './model/PatchedTimesheetSubmissionRequest';
import PatchedValueStatementRequest from './model/PatchedValueStatementRequest';
import PatchedWorkOrderRequest from './model/PatchedWorkOrderRequest';
import PlatformNameEnum from './model/PlatformNameEnum';
import ProgressEnum from './model/ProgressEnum';
import QuickNote from './model/QuickNote';
import QuickNoteRequest from './model/QuickNoteRequest';
import Region from './model/Region';
import RegionRequest from './model/RegionRequest';
import Section from './model/Section';
import SocialMedia from './model/SocialMedia';
import SocialMediaRequest from './model/SocialMediaRequest';
import Status300Enum from './model/Status300Enum';
import Task from './model/Task';
import TaskRequest from './model/TaskRequest';
import TimesheetEntry from './model/TimesheetEntry';
import TimesheetEntryRequest from './model/TimesheetEntryRequest';
import TimesheetSubmission from './model/TimesheetSubmission';
import TimesheetSubmissionRequest from './model/TimesheetSubmissionRequest';
import Value from './model/Value';
import ValueStatement from './model/ValueStatement';
import ValueStatementRequest from './model/ValueStatementRequest';
import WorkOrder from './model/WorkOrder';
import WorkOrderRequest from './model/WorkOrderRequest';
import AvailableApi from './api/AvailableApi';
import BillingUnitApi from './api/BillingUnitApi';
import CapabilityStatementApi from './api/CapabilityStatementApi';
import ClientApi from './api/ClientApi';
import ContactApi from './api/ContactApi';
import EmployeeApi from './api/EmployeeApi';
import ExpertiseApi from './api/ExpertiseApi';
import FeatureSectionsApi from './api/FeatureSectionsApi';
import FooterCtaApi from './api/FooterCtaApi';
import HeroSectionApi from './api/HeroSectionApi';
import LeaveEntryApi from './api/LeaveEntryApi';
import LegalSectionApi from './api/LegalSectionApi';
import LocationSectionApi from './api/LocationSectionApi';
import LocationsApi from './api/LocationsApi';
import OperationApi from './api/OperationApi';
import OrganisationLogosApi from './api/OrganisationLogosApi';
import OrganisationSectionApi from './api/OrganisationSectionApi';
import QuickNoteApi from './api/QuickNoteApi';
import RegionApi from './api/RegionApi';
import SectionsApi from './api/SectionsApi';
import ServiceSectionApi from './api/ServiceSectionApi';
import ServicesApi from './api/ServicesApi';
import SiteConfigApi from './api/SiteConfigApi';
import SocialMediaApi from './api/SocialMediaApi';
import TaskApi from './api/TaskApi';
import TimesheetEntryApi from './api/TimesheetEntryApi';
import TimesheetSubmissionApi from './api/TimesheetSubmissionApi';
import ValueStatementApi from './api/ValueStatementApi';
import ValuesApi from './api/ValuesApi';
import WorkOrderApi from './api/WorkOrderApi';


/**
* API for regions, clients, operations, tasks, timesheets, submissions &amp; approvals.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TimesheetApi = require('index'); // See note below*.
* var xxxSvc = new TimesheetApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TimesheetApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TimesheetApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TimesheetApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BillingUnit model constructor.
     * @property {module:model/BillingUnit}
     */
    BillingUnit,

    /**
     * The BillingUnitRequest model constructor.
     * @property {module:model/BillingUnitRequest}
     */
    BillingUnitRequest,

    /**
     * The CapabilityStatement model constructor.
     * @property {module:model/CapabilityStatement}
     */
    CapabilityStatement,

    /**
     * The CapabilityStatementRequest model constructor.
     * @property {module:model/CapabilityStatementRequest}
     */
    CapabilityStatementRequest,

    /**
     * The Client model constructor.
     * @property {module:model/Client}
     */
    Client,

    /**
     * The ClientRequest model constructor.
     * @property {module:model/ClientRequest}
     */
    ClientRequest,

    /**
     * The ContactMessage model constructor.
     * @property {module:model/ContactMessage}
     */
    ContactMessage,

    /**
     * The ContactMessageRequest model constructor.
     * @property {module:model/ContactMessageRequest}
     */
    ContactMessageRequest,

    /**
     * The Employee model constructor.
     * @property {module:model/Employee}
     */
    Employee,

    /**
     * The EmployeeRequest model constructor.
     * @property {module:model/EmployeeRequest}
     */
    EmployeeRequest,

    /**
     * The Expertise model constructor.
     * @property {module:model/Expertise}
     */
    Expertise,

    /**
     * The FeatureSection model constructor.
     * @property {module:model/FeatureSection}
     */
    FeatureSection,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The LeaveEntry model constructor.
     * @property {module:model/LeaveEntry}
     */
    LeaveEntry,

    /**
     * The LeaveEntryRequest model constructor.
     * @property {module:model/LeaveEntryRequest}
     */
    LeaveEntryRequest,

    /**
     * The LeaveTypeEnum model constructor.
     * @property {module:model/LeaveTypeEnum}
     */
    LeaveTypeEnum,

    /**
     * The LegalSection model constructor.
     * @property {module:model/LegalSection}
     */
    LegalSection,

    /**
     * The LegalSectionRequest model constructor.
     * @property {module:model/LegalSectionRequest}
     */
    LegalSectionRequest,

    /**
     * The LocationOffice model constructor.
     * @property {module:model/LocationOffice}
     */
    LocationOffice,

    /**
     * The LocationSection model constructor.
     * @property {module:model/LocationSection}
     */
    LocationSection,

    /**
     * The LocationSectionRequest model constructor.
     * @property {module:model/LocationSectionRequest}
     */
    LocationSectionRequest,

    /**
     * The Operation model constructor.
     * @property {module:model/Operation}
     */
    Operation,

    /**
     * The OperationRequest model constructor.
     * @property {module:model/OperationRequest}
     */
    OperationRequest,

    /**
     * The OperationStatusEnum model constructor.
     * @property {module:model/OperationStatusEnum}
     */
    OperationStatusEnum,

    /**
     * The OrganisationLogos model constructor.
     * @property {module:model/OrganisationLogos}
     */
    OrganisationLogos,

    /**
     * The OrganisationSection model constructor.
     * @property {module:model/OrganisationSection}
     */
    OrganisationSection,

    /**
     * The OrganisationSectionRequest model constructor.
     * @property {module:model/OrganisationSectionRequest}
     */
    OrganisationSectionRequest,

    /**
     * The PaginatedBillingUnitList model constructor.
     * @property {module:model/PaginatedBillingUnitList}
     */
    PaginatedBillingUnitList,

    /**
     * The PaginatedCapabilityStatementList model constructor.
     * @property {module:model/PaginatedCapabilityStatementList}
     */
    PaginatedCapabilityStatementList,

    /**
     * The PaginatedClientList model constructor.
     * @property {module:model/PaginatedClientList}
     */
    PaginatedClientList,

    /**
     * The PaginatedEmployeeList model constructor.
     * @property {module:model/PaginatedEmployeeList}
     */
    PaginatedEmployeeList,

    /**
     * The PaginatedExpertiseList model constructor.
     * @property {module:model/PaginatedExpertiseList}
     */
    PaginatedExpertiseList,

    /**
     * The PaginatedFeatureSectionList model constructor.
     * @property {module:model/PaginatedFeatureSectionList}
     */
    PaginatedFeatureSectionList,

    /**
     * The PaginatedLeaveEntryList model constructor.
     * @property {module:model/PaginatedLeaveEntryList}
     */
    PaginatedLeaveEntryList,

    /**
     * The PaginatedLocationOfficeList model constructor.
     * @property {module:model/PaginatedLocationOfficeList}
     */
    PaginatedLocationOfficeList,

    /**
     * The PaginatedOperationList model constructor.
     * @property {module:model/PaginatedOperationList}
     */
    PaginatedOperationList,

    /**
     * The PaginatedOrganisationLogosList model constructor.
     * @property {module:model/PaginatedOrganisationLogosList}
     */
    PaginatedOrganisationLogosList,

    /**
     * The PaginatedOrganisationSectionList model constructor.
     * @property {module:model/PaginatedOrganisationSectionList}
     */
    PaginatedOrganisationSectionList,

    /**
     * The PaginatedQuickNoteList model constructor.
     * @property {module:model/PaginatedQuickNoteList}
     */
    PaginatedQuickNoteList,

    /**
     * The PaginatedRegionList model constructor.
     * @property {module:model/PaginatedRegionList}
     */
    PaginatedRegionList,

    /**
     * The PaginatedSectionList model constructor.
     * @property {module:model/PaginatedSectionList}
     */
    PaginatedSectionList,

    /**
     * The PaginatedSocialMediaList model constructor.
     * @property {module:model/PaginatedSocialMediaList}
     */
    PaginatedSocialMediaList,

    /**
     * The PaginatedTaskList model constructor.
     * @property {module:model/PaginatedTaskList}
     */
    PaginatedTaskList,

    /**
     * The PaginatedTimesheetEntryList model constructor.
     * @property {module:model/PaginatedTimesheetEntryList}
     */
    PaginatedTimesheetEntryList,

    /**
     * The PaginatedTimesheetSubmissionList model constructor.
     * @property {module:model/PaginatedTimesheetSubmissionList}
     */
    PaginatedTimesheetSubmissionList,

    /**
     * The PaginatedValueList model constructor.
     * @property {module:model/PaginatedValueList}
     */
    PaginatedValueList,

    /**
     * The PaginatedValueStatementList model constructor.
     * @property {module:model/PaginatedValueStatementList}
     */
    PaginatedValueStatementList,

    /**
     * The PaginatedWorkOrderList model constructor.
     * @property {module:model/PaginatedWorkOrderList}
     */
    PaginatedWorkOrderList,

    /**
     * The PatchedBillingUnitRequest model constructor.
     * @property {module:model/PatchedBillingUnitRequest}
     */
    PatchedBillingUnitRequest,

    /**
     * The PatchedCapabilityStatementRequest model constructor.
     * @property {module:model/PatchedCapabilityStatementRequest}
     */
    PatchedCapabilityStatementRequest,

    /**
     * The PatchedClientRequest model constructor.
     * @property {module:model/PatchedClientRequest}
     */
    PatchedClientRequest,

    /**
     * The PatchedEmployeeRequest model constructor.
     * @property {module:model/PatchedEmployeeRequest}
     */
    PatchedEmployeeRequest,

    /**
     * The PatchedLeaveEntryRequest model constructor.
     * @property {module:model/PatchedLeaveEntryRequest}
     */
    PatchedLeaveEntryRequest,

    /**
     * The PatchedLegalSectionRequest model constructor.
     * @property {module:model/PatchedLegalSectionRequest}
     */
    PatchedLegalSectionRequest,

    /**
     * The PatchedLocationSectionRequest model constructor.
     * @property {module:model/PatchedLocationSectionRequest}
     */
    PatchedLocationSectionRequest,

    /**
     * The PatchedOperationRequest model constructor.
     * @property {module:model/PatchedOperationRequest}
     */
    PatchedOperationRequest,

    /**
     * The PatchedOrganisationSectionRequest model constructor.
     * @property {module:model/PatchedOrganisationSectionRequest}
     */
    PatchedOrganisationSectionRequest,

    /**
     * The PatchedQuickNoteRequest model constructor.
     * @property {module:model/PatchedQuickNoteRequest}
     */
    PatchedQuickNoteRequest,

    /**
     * The PatchedRegionRequest model constructor.
     * @property {module:model/PatchedRegionRequest}
     */
    PatchedRegionRequest,

    /**
     * The PatchedSocialMediaRequest model constructor.
     * @property {module:model/PatchedSocialMediaRequest}
     */
    PatchedSocialMediaRequest,

    /**
     * The PatchedTaskRequest model constructor.
     * @property {module:model/PatchedTaskRequest}
     */
    PatchedTaskRequest,

    /**
     * The PatchedTimesheetEntryRequest model constructor.
     * @property {module:model/PatchedTimesheetEntryRequest}
     */
    PatchedTimesheetEntryRequest,

    /**
     * The PatchedTimesheetSubmissionRequest model constructor.
     * @property {module:model/PatchedTimesheetSubmissionRequest}
     */
    PatchedTimesheetSubmissionRequest,

    /**
     * The PatchedValueStatementRequest model constructor.
     * @property {module:model/PatchedValueStatementRequest}
     */
    PatchedValueStatementRequest,

    /**
     * The PatchedWorkOrderRequest model constructor.
     * @property {module:model/PatchedWorkOrderRequest}
     */
    PatchedWorkOrderRequest,

    /**
     * The PlatformNameEnum model constructor.
     * @property {module:model/PlatformNameEnum}
     */
    PlatformNameEnum,

    /**
     * The ProgressEnum model constructor.
     * @property {module:model/ProgressEnum}
     */
    ProgressEnum,

    /**
     * The QuickNote model constructor.
     * @property {module:model/QuickNote}
     */
    QuickNote,

    /**
     * The QuickNoteRequest model constructor.
     * @property {module:model/QuickNoteRequest}
     */
    QuickNoteRequest,

    /**
     * The Region model constructor.
     * @property {module:model/Region}
     */
    Region,

    /**
     * The RegionRequest model constructor.
     * @property {module:model/RegionRequest}
     */
    RegionRequest,

    /**
     * The Section model constructor.
     * @property {module:model/Section}
     */
    Section,

    /**
     * The SocialMedia model constructor.
     * @property {module:model/SocialMedia}
     */
    SocialMedia,

    /**
     * The SocialMediaRequest model constructor.
     * @property {module:model/SocialMediaRequest}
     */
    SocialMediaRequest,

    /**
     * The Status300Enum model constructor.
     * @property {module:model/Status300Enum}
     */
    Status300Enum,

    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task,

    /**
     * The TaskRequest model constructor.
     * @property {module:model/TaskRequest}
     */
    TaskRequest,

    /**
     * The TimesheetEntry model constructor.
     * @property {module:model/TimesheetEntry}
     */
    TimesheetEntry,

    /**
     * The TimesheetEntryRequest model constructor.
     * @property {module:model/TimesheetEntryRequest}
     */
    TimesheetEntryRequest,

    /**
     * The TimesheetSubmission model constructor.
     * @property {module:model/TimesheetSubmission}
     */
    TimesheetSubmission,

    /**
     * The TimesheetSubmissionRequest model constructor.
     * @property {module:model/TimesheetSubmissionRequest}
     */
    TimesheetSubmissionRequest,

    /**
     * The Value model constructor.
     * @property {module:model/Value}
     */
    Value,

    /**
     * The ValueStatement model constructor.
     * @property {module:model/ValueStatement}
     */
    ValueStatement,

    /**
     * The ValueStatementRequest model constructor.
     * @property {module:model/ValueStatementRequest}
     */
    ValueStatementRequest,

    /**
     * The WorkOrder model constructor.
     * @property {module:model/WorkOrder}
     */
    WorkOrder,

    /**
     * The WorkOrderRequest model constructor.
     * @property {module:model/WorkOrderRequest}
     */
    WorkOrderRequest,

    /**
    * The AvailableApi service constructor.
    * @property {module:api/AvailableApi}
    */
    AvailableApi,

    /**
    * The BillingUnitApi service constructor.
    * @property {module:api/BillingUnitApi}
    */
    BillingUnitApi,

    /**
    * The CapabilityStatementApi service constructor.
    * @property {module:api/CapabilityStatementApi}
    */
    CapabilityStatementApi,

    /**
    * The ClientApi service constructor.
    * @property {module:api/ClientApi}
    */
    ClientApi,

    /**
    * The ContactApi service constructor.
    * @property {module:api/ContactApi}
    */
    ContactApi,

    /**
    * The EmployeeApi service constructor.
    * @property {module:api/EmployeeApi}
    */
    EmployeeApi,

    /**
    * The ExpertiseApi service constructor.
    * @property {module:api/ExpertiseApi}
    */
    ExpertiseApi,

    /**
    * The FeatureSectionsApi service constructor.
    * @property {module:api/FeatureSectionsApi}
    */
    FeatureSectionsApi,

    /**
    * The FooterCtaApi service constructor.
    * @property {module:api/FooterCtaApi}
    */
    FooterCtaApi,

    /**
    * The HeroSectionApi service constructor.
    * @property {module:api/HeroSectionApi}
    */
    HeroSectionApi,

    /**
    * The LeaveEntryApi service constructor.
    * @property {module:api/LeaveEntryApi}
    */
    LeaveEntryApi,

    /**
    * The LegalSectionApi service constructor.
    * @property {module:api/LegalSectionApi}
    */
    LegalSectionApi,

    /**
    * The LocationSectionApi service constructor.
    * @property {module:api/LocationSectionApi}
    */
    LocationSectionApi,

    /**
    * The LocationsApi service constructor.
    * @property {module:api/LocationsApi}
    */
    LocationsApi,

    /**
    * The OperationApi service constructor.
    * @property {module:api/OperationApi}
    */
    OperationApi,

    /**
    * The OrganisationLogosApi service constructor.
    * @property {module:api/OrganisationLogosApi}
    */
    OrganisationLogosApi,

    /**
    * The OrganisationSectionApi service constructor.
    * @property {module:api/OrganisationSectionApi}
    */
    OrganisationSectionApi,

    /**
    * The QuickNoteApi service constructor.
    * @property {module:api/QuickNoteApi}
    */
    QuickNoteApi,

    /**
    * The RegionApi service constructor.
    * @property {module:api/RegionApi}
    */
    RegionApi,

    /**
    * The SectionsApi service constructor.
    * @property {module:api/SectionsApi}
    */
    SectionsApi,

    /**
    * The ServiceSectionApi service constructor.
    * @property {module:api/ServiceSectionApi}
    */
    ServiceSectionApi,

    /**
    * The ServicesApi service constructor.
    * @property {module:api/ServicesApi}
    */
    ServicesApi,

    /**
    * The SiteConfigApi service constructor.
    * @property {module:api/SiteConfigApi}
    */
    SiteConfigApi,

    /**
    * The SocialMediaApi service constructor.
    * @property {module:api/SocialMediaApi}
    */
    SocialMediaApi,

    /**
    * The TaskApi service constructor.
    * @property {module:api/TaskApi}
    */
    TaskApi,

    /**
    * The TimesheetEntryApi service constructor.
    * @property {module:api/TimesheetEntryApi}
    */
    TimesheetEntryApi,

    /**
    * The TimesheetSubmissionApi service constructor.
    * @property {module:api/TimesheetSubmissionApi}
    */
    TimesheetSubmissionApi,

    /**
    * The ValueStatementApi service constructor.
    * @property {module:api/ValueStatementApi}
    */
    ValueStatementApi,

    /**
    * The ValuesApi service constructor.
    * @property {module:api/ValuesApi}
    */
    ValuesApi,

    /**
    * The WorkOrderApi service constructor.
    * @property {module:api/WorkOrderApi}
    */
    WorkOrderApi
};
