/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.BillingUnitApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BillingUnitApi', function() {
    describe('billingUnitsCreate', function() {
      it('should call billingUnitsCreate successfully', function(done) {
        //uncomment below and update the code to test billingUnitsCreate
        //instance.billingUnitsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('billingUnitsDestroy', function() {
      it('should call billingUnitsDestroy successfully', function(done) {
        //uncomment below and update the code to test billingUnitsDestroy
        //instance.billingUnitsDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('billingUnitsList', function() {
      it('should call billingUnitsList successfully', function(done) {
        //uncomment below and update the code to test billingUnitsList
        //instance.billingUnitsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('billingUnitsPartialUpdate', function() {
      it('should call billingUnitsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test billingUnitsPartialUpdate
        //instance.billingUnitsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('billingUnitsRetrieve', function() {
      it('should call billingUnitsRetrieve successfully', function(done) {
        //uncomment below and update the code to test billingUnitsRetrieve
        //instance.billingUnitsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('billingUnitsUpdate', function() {
      it('should call billingUnitsUpdate successfully', function(done) {
        //uncomment below and update the code to test billingUnitsUpdate
        //instance.billingUnitsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
