/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.CapabilityStatementApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CapabilityStatementApi', function() {
    describe('capabilityStatementCreate', function() {
      it('should call capabilityStatementCreate successfully', function(done) {
        //uncomment below and update the code to test capabilityStatementCreate
        //instance.capabilityStatementCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('capabilityStatementDestroy', function() {
      it('should call capabilityStatementDestroy successfully', function(done) {
        //uncomment below and update the code to test capabilityStatementDestroy
        //instance.capabilityStatementDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('capabilityStatementList', function() {
      it('should call capabilityStatementList successfully', function(done) {
        //uncomment below and update the code to test capabilityStatementList
        //instance.capabilityStatementList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('capabilityStatementPartialUpdate', function() {
      it('should call capabilityStatementPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test capabilityStatementPartialUpdate
        //instance.capabilityStatementPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('capabilityStatementRetrieve', function() {
      it('should call capabilityStatementRetrieve successfully', function(done) {
        //uncomment below and update the code to test capabilityStatementRetrieve
        //instance.capabilityStatementRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('capabilityStatementUpdate', function() {
      it('should call capabilityStatementUpdate successfully', function(done) {
        //uncomment below and update the code to test capabilityStatementUpdate
        //instance.capabilityStatementUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
