/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.LeaveEntryApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LeaveEntryApi', function() {
    describe('leaveEntriesCreate', function() {
      it('should call leaveEntriesCreate successfully', function(done) {
        //uncomment below and update the code to test leaveEntriesCreate
        //instance.leaveEntriesCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leaveEntriesDestroy', function() {
      it('should call leaveEntriesDestroy successfully', function(done) {
        //uncomment below and update the code to test leaveEntriesDestroy
        //instance.leaveEntriesDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leaveEntriesList', function() {
      it('should call leaveEntriesList successfully', function(done) {
        //uncomment below and update the code to test leaveEntriesList
        //instance.leaveEntriesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leaveEntriesPartialUpdate', function() {
      it('should call leaveEntriesPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test leaveEntriesPartialUpdate
        //instance.leaveEntriesPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leaveEntriesRetrieve', function() {
      it('should call leaveEntriesRetrieve successfully', function(done) {
        //uncomment below and update the code to test leaveEntriesRetrieve
        //instance.leaveEntriesRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leaveEntriesUpdate', function() {
      it('should call leaveEntriesUpdate successfully', function(done) {
        //uncomment below and update the code to test leaveEntriesUpdate
        //instance.leaveEntriesUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
