/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.LocationSectionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LocationSectionApi', function() {
    describe('locationSectionPartialUpdate', function() {
      it('should call locationSectionPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test locationSectionPartialUpdate
        //instance.locationSectionPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('locationSectionRetrieve', function() {
      it('should call locationSectionRetrieve successfully', function(done) {
        //uncomment below and update the code to test locationSectionRetrieve
        //instance.locationSectionRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('locationSectionUpdate', function() {
      it('should call locationSectionUpdate successfully', function(done) {
        //uncomment below and update the code to test locationSectionUpdate
        //instance.locationSectionUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
