/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.QuickNoteApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuickNoteApi', function() {
    describe('quicknotesCreate', function() {
      it('should call quicknotesCreate successfully', function(done) {
        //uncomment below and update the code to test quicknotesCreate
        //instance.quicknotesCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quicknotesDestroy', function() {
      it('should call quicknotesDestroy successfully', function(done) {
        //uncomment below and update the code to test quicknotesDestroy
        //instance.quicknotesDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quicknotesList', function() {
      it('should call quicknotesList successfully', function(done) {
        //uncomment below and update the code to test quicknotesList
        //instance.quicknotesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quicknotesPartialUpdate', function() {
      it('should call quicknotesPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test quicknotesPartialUpdate
        //instance.quicknotesPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quicknotesRetrieve', function() {
      it('should call quicknotesRetrieve successfully', function(done) {
        //uncomment below and update the code to test quicknotesRetrieve
        //instance.quicknotesRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quicknotesUpdate', function() {
      it('should call quicknotesUpdate successfully', function(done) {
        //uncomment below and update the code to test quicknotesUpdate
        //instance.quicknotesUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
