/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.SocialMediaApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SocialMediaApi', function() {
    describe('socialMediaCreate', function() {
      it('should call socialMediaCreate successfully', function(done) {
        //uncomment below and update the code to test socialMediaCreate
        //instance.socialMediaCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('socialMediaDestroy', function() {
      it('should call socialMediaDestroy successfully', function(done) {
        //uncomment below and update the code to test socialMediaDestroy
        //instance.socialMediaDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('socialMediaList', function() {
      it('should call socialMediaList successfully', function(done) {
        //uncomment below and update the code to test socialMediaList
        //instance.socialMediaList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('socialMediaPartialUpdate', function() {
      it('should call socialMediaPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test socialMediaPartialUpdate
        //instance.socialMediaPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('socialMediaRetrieve', function() {
      it('should call socialMediaRetrieve successfully', function(done) {
        //uncomment below and update the code to test socialMediaRetrieve
        //instance.socialMediaRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('socialMediaUpdate', function() {
      it('should call socialMediaUpdate successfully', function(done) {
        //uncomment below and update the code to test socialMediaUpdate
        //instance.socialMediaUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
