/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.TimesheetSubmissionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TimesheetSubmissionApi', function() {
    describe('submissionsApproveCreate', function() {
      it('should call submissionsApproveCreate successfully', function(done) {
        //uncomment below and update the code to test submissionsApproveCreate
        //instance.submissionsApproveCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsCreate', function() {
      it('should call submissionsCreate successfully', function(done) {
        //uncomment below and update the code to test submissionsCreate
        //instance.submissionsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsDestroy', function() {
      it('should call submissionsDestroy successfully', function(done) {
        //uncomment below and update the code to test submissionsDestroy
        //instance.submissionsDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsList', function() {
      it('should call submissionsList successfully', function(done) {
        //uncomment below and update the code to test submissionsList
        //instance.submissionsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsLockCreate', function() {
      it('should call submissionsLockCreate successfully', function(done) {
        //uncomment below and update the code to test submissionsLockCreate
        //instance.submissionsLockCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsPartialUpdate', function() {
      it('should call submissionsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test submissionsPartialUpdate
        //instance.submissionsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsRejectCreate', function() {
      it('should call submissionsRejectCreate successfully', function(done) {
        //uncomment below and update the code to test submissionsRejectCreate
        //instance.submissionsRejectCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsRetrieve', function() {
      it('should call submissionsRetrieve successfully', function(done) {
        //uncomment below and update the code to test submissionsRetrieve
        //instance.submissionsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsSubmitCreate', function() {
      it('should call submissionsSubmitCreate successfully', function(done) {
        //uncomment below and update the code to test submissionsSubmitCreate
        //instance.submissionsSubmitCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submissionsUpdate', function() {
      it('should call submissionsUpdate successfully', function(done) {
        //uncomment below and update the code to test submissionsUpdate
        //instance.submissionsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
