/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.ValueStatementApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValueStatementApi', function() {
    describe('valueStatementCreate', function() {
      it('should call valueStatementCreate successfully', function(done) {
        //uncomment below and update the code to test valueStatementCreate
        //instance.valueStatementCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('valueStatementDestroy', function() {
      it('should call valueStatementDestroy successfully', function(done) {
        //uncomment below and update the code to test valueStatementDestroy
        //instance.valueStatementDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('valueStatementList', function() {
      it('should call valueStatementList successfully', function(done) {
        //uncomment below and update the code to test valueStatementList
        //instance.valueStatementList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('valueStatementPartialUpdate', function() {
      it('should call valueStatementPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test valueStatementPartialUpdate
        //instance.valueStatementPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('valueStatementRetrieve', function() {
      it('should call valueStatementRetrieve successfully', function(done) {
        //uncomment below and update the code to test valueStatementRetrieve
        //instance.valueStatementRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('valueStatementUpdate', function() {
      it('should call valueStatementUpdate successfully', function(done) {
        //uncomment below and update the code to test valueStatementUpdate
        //instance.valueStatementUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
