/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.WorkOrderApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WorkOrderApi', function() {
    describe('workordersCreate', function() {
      it('should call workordersCreate successfully', function(done) {
        //uncomment below and update the code to test workordersCreate
        //instance.workordersCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workordersDestroy', function() {
      it('should call workordersDestroy successfully', function(done) {
        //uncomment below and update the code to test workordersDestroy
        //instance.workordersDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workordersList', function() {
      it('should call workordersList successfully', function(done) {
        //uncomment below and update the code to test workordersList
        //instance.workordersList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workordersPartialUpdate', function() {
      it('should call workordersPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test workordersPartialUpdate
        //instance.workordersPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workordersRetrieve', function() {
      it('should call workordersRetrieve successfully', function(done) {
        //uncomment below and update the code to test workordersRetrieve
        //instance.workordersRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workordersUpdate', function() {
      it('should call workordersUpdate successfully', function(done) {
        //uncomment below and update the code to test workordersUpdate
        //instance.workordersUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
