/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BillingUnitRequest model module.
 * @module model/BillingUnitRequest
 * @version 1.0.0
 */
class BillingUnitRequest {
    /**
     * Constructs a new <code>BillingUnitRequest</code>.
     * Minimal BillingUnit serializer for listing and admin usage. Serializador mínimo de BillingUnit para listado y uso admin.
     * @alias module:model/BillingUnitRequest
     * @param code {String} System identifier (immutable after creation)
     * @param label {String} Human-readable label (editable)
     */
    constructor(code, label) { 
        
        BillingUnitRequest.initialize(this, code, label);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, label) { 
        obj['code'] = code;
        obj['label'] = label;
    }

    /**
     * Constructs a <code>BillingUnitRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BillingUnitRequest} obj Optional instance to populate.
     * @return {module:model/BillingUnitRequest} The populated <code>BillingUnitRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillingUnitRequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BillingUnitRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BillingUnitRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BillingUnitRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }

        return true;
    }


}

BillingUnitRequest.RequiredProperties = ["code", "label"];

/**
 * System identifier (immutable after creation)
 * @member {String} code
 */
BillingUnitRequest.prototype['code'] = undefined;

/**
 * Human-readable label (editable)
 * @member {String} label
 */
BillingUnitRequest.prototype['label'] = undefined;

/**
 * Whether this billing unit is currently available
 * @member {Boolean} active
 */
BillingUnitRequest.prototype['active'] = undefined;






export default BillingUnitRequest;

