/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Client model module.
 * @module model/Client
 * @version 1.0.0
 */
class Client {
    /**
     * Constructs a new <code>Client</code>.
     * Minimal Client serializer. Serializador mínimo de Client.
     * @alias module:model/Client
     * @param id {Number} 
     * @param name {String} Client name
     * @param allowedBillingUnits {Array.<Number>} 
     */
    constructor(id, name, allowedBillingUnits) { 
        
        Client.initialize(this, id, name, allowedBillingUnits);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, allowedBillingUnits) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['allowed_billing_units'] = allowedBillingUnits;
    }

    /**
     * Constructs a <code>Client</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Client} obj Optional instance to populate.
     * @return {module:model/Client} The populated <code>Client</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Client();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('allowed_billing_units')) {
                obj['allowed_billing_units'] = ApiClient.convertToType(data['allowed_billing_units'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Client</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Client</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Client.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['allowed_billing_units'])) {
            throw new Error("Expected the field `allowed_billing_units` to be an array in the JSON data but got " + data['allowed_billing_units']);
        }

        return true;
    }


}

Client.RequiredProperties = ["id", "name", "allowed_billing_units"];

/**
 * @member {Number} id
 */
Client.prototype['id'] = undefined;

/**
 * Client name
 * @member {String} name
 */
Client.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} allowed_billing_units
 */
Client.prototype['allowed_billing_units'] = undefined;






export default Client;

