/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactMessageRequest model module.
 * @module model/ContactMessageRequest
 * @version 1.0.0
 */
class ContactMessageRequest {
    /**
     * Constructs a new <code>ContactMessageRequest</code>.
     * Serializer for the ContactMessage model. Validates and processes incoming contact form submissions. All fields are required except created_at which is auto-generated.
     * @alias module:model/ContactMessageRequest
     * @param name {String} User's name
     * @param email {String} User's email address
     * @param message {String} The message content
     */
    constructor(name, email, message) { 
        
        ContactMessageRequest.initialize(this, name, email, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, email, message) { 
        obj['name'] = name;
        obj['email'] = email;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>ContactMessageRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactMessageRequest} obj Optional instance to populate.
     * @return {module:model/ContactMessageRequest} The populated <code>ContactMessageRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactMessageRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactMessageRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactMessageRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContactMessageRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

ContactMessageRequest.RequiredProperties = ["name", "email", "message"];

/**
 * User's name
 * @member {String} name
 */
ContactMessageRequest.prototype['name'] = undefined;

/**
 * User's email address
 * @member {String} email
 */
ContactMessageRequest.prototype['email'] = undefined;

/**
 * The message content
 * @member {String} message
 */
ContactMessageRequest.prototype['message'] = undefined;






export default ContactMessageRequest;

