/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactMessage model module.
 * @module model/ContactMessage
 * @version 1.0.0
 */
class ContactMessage {
    /**
     * Constructs a new <code>ContactMessage</code>.
     * Serializer for the ContactMessage model. Validates and processes incoming contact form submissions. All fields are required except created_at which is auto-generated.
     * @alias module:model/ContactMessage
     * @param id {Number} 
     * @param name {String} User's name
     * @param email {String} User's email address
     * @param message {String} The message content
     * @param createdAt {Date} Timestamp when the message was created
     */
    constructor(id, name, email, message, createdAt) { 
        
        ContactMessage.initialize(this, id, name, email, message, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, email, message, createdAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['email'] = email;
        obj['message'] = message;
        obj['created_at'] = createdAt;
    }

    /**
     * Constructs a <code>ContactMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactMessage} obj Optional instance to populate.
     * @return {module:model/ContactMessage} The populated <code>ContactMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactMessage();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContactMessage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

ContactMessage.RequiredProperties = ["id", "name", "email", "message", "created_at"];

/**
 * @member {Number} id
 */
ContactMessage.prototype['id'] = undefined;

/**
 * User's name
 * @member {String} name
 */
ContactMessage.prototype['name'] = undefined;

/**
 * User's email address
 * @member {String} email
 */
ContactMessage.prototype['email'] = undefined;

/**
 * The message content
 * @member {String} message
 */
ContactMessage.prototype['message'] = undefined;

/**
 * Timestamp when the message was created
 * @member {Date} created_at
 */
ContactMessage.prototype['created_at'] = undefined;






export default ContactMessage;

