/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LeaveTypeEnum.
* @enum {}
* @readonly
*/
export default class LeaveTypeEnum {
    
        /**
         * value: "sick"
         * @const
         */
        "sick" = "sick";

    
        /**
         * value: "annual"
         * @const
         */
        "annual" = "annual";

    
        /**
         * value: "unpaid"
         * @const
         */
        "unpaid" = "unpaid";

    
        /**
         * value: "other"
         * @const
         */
        "other" = "other";

    

    /**
    * Returns a <code>LeaveTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LeaveTypeEnum} The enum <code>LeaveTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

