/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LeaveTypeEnum from './LeaveTypeEnum';

/**
 * The LeaveEntryRequest model module.
 * @module model/LeaveEntryRequest
 * @version 1.0.0
 */
class LeaveEntryRequest {
    /**
     * Constructs a new <code>LeaveEntryRequest</code>.
     * Serializer for LeaveEntry to expose CRUD fields to the API. Serializador para LeaveEntry que expone campos CRUD al API.
     * @alias module:model/LeaveEntryRequest
     * @param startDate {Date} 
     * @param leaveType {module:model/LeaveTypeEnum} 
     */
    constructor(startDate, leaveType) { 
        
        LeaveEntryRequest.initialize(this, startDate, leaveType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startDate, leaveType) { 
        obj['start_date'] = startDate;
        obj['leave_type'] = leaveType;
    }

    /**
     * Constructs a <code>LeaveEntryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LeaveEntryRequest} obj Optional instance to populate.
     * @return {module:model/LeaveEntryRequest} The populated <code>LeaveEntryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeaveEntryRequest();

            if (data.hasOwnProperty('employee')) {
                obj['employee'] = ApiClient.convertToType(data['employee'], 'Number');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('leave_type')) {
                obj['leave_type'] = LeaveTypeEnum.constructFromObject(data['leave_type']);
            }
            if (data.hasOwnProperty('hours_or_days')) {
                obj['hours_or_days'] = ApiClient.convertToType(data['hours_or_days'], 'Number');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LeaveEntryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LeaveEntryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LeaveEntryRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['hours_or_days'] && !(typeof data['hours_or_days'] === 'string' || data['hours_or_days'] instanceof String)) {
            throw new Error("Expected the field `hours_or_days` to be a primitive type in the JSON string but got " + data['hours_or_days']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}

LeaveEntryRequest.RequiredProperties = ["start_date", "leave_type"];

/**
 * @member {Number} employee
 */
LeaveEntryRequest.prototype['employee'] = undefined;

/**
 * @member {Date} start_date
 */
LeaveEntryRequest.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
LeaveEntryRequest.prototype['end_date'] = undefined;

/**
 * @member {module:model/LeaveTypeEnum} leave_type
 */
LeaveEntryRequest.prototype['leave_type'] = undefined;

/**
 * EN: Optional quantity of leave taken (hours or days). ES: Cantidad opcional de licencia tomada (horas o días).
 * @member {Number} hours_or_days
 */
LeaveEntryRequest.prototype['hours_or_days'] = undefined;

/**
 * @member {String} notes
 */
LeaveEntryRequest.prototype['notes'] = undefined;






export default LeaveEntryRequest;

