/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LegalSectionRequest model module.
 * @module model/LegalSectionRequest
 * @version 1.0.0
 */
class LegalSectionRequest {
    /**
     * Constructs a new <code>LegalSectionRequest</code>.
     * Serializer for the LegalSection model. Provides company disclaimer, privacy policy, and terms &amp; conditions information.
     * @alias module:model/LegalSectionRequest
     * @param companyDisclaimer {String} 
     * @param privacyPolicyUrl {String} 
     * @param termsUrl {String} 
     */
    constructor(companyDisclaimer, privacyPolicyUrl, termsUrl) { 
        
        LegalSectionRequest.initialize(this, companyDisclaimer, privacyPolicyUrl, termsUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, companyDisclaimer, privacyPolicyUrl, termsUrl) { 
        obj['company_disclaimer'] = companyDisclaimer;
        obj['privacy_policy_url'] = privacyPolicyUrl;
        obj['terms_url'] = termsUrl;
    }

    /**
     * Constructs a <code>LegalSectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LegalSectionRequest} obj Optional instance to populate.
     * @return {module:model/LegalSectionRequest} The populated <code>LegalSectionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LegalSectionRequest();

            if (data.hasOwnProperty('company_disclaimer')) {
                obj['company_disclaimer'] = ApiClient.convertToType(data['company_disclaimer'], 'String');
            }
            if (data.hasOwnProperty('privacy_policy_title')) {
                obj['privacy_policy_title'] = ApiClient.convertToType(data['privacy_policy_title'], 'String');
            }
            if (data.hasOwnProperty('privacy_policy_content')) {
                obj['privacy_policy_content'] = ApiClient.convertToType(data['privacy_policy_content'], 'String');
            }
            if (data.hasOwnProperty('privacy_policy_url')) {
                obj['privacy_policy_url'] = ApiClient.convertToType(data['privacy_policy_url'], 'String');
            }
            if (data.hasOwnProperty('terms_title')) {
                obj['terms_title'] = ApiClient.convertToType(data['terms_title'], 'String');
            }
            if (data.hasOwnProperty('terms_content')) {
                obj['terms_content'] = ApiClient.convertToType(data['terms_content'], 'String');
            }
            if (data.hasOwnProperty('terms_url')) {
                obj['terms_url'] = ApiClient.convertToType(data['terms_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LegalSectionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LegalSectionRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LegalSectionRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['company_disclaimer'] && !(typeof data['company_disclaimer'] === 'string' || data['company_disclaimer'] instanceof String)) {
            throw new Error("Expected the field `company_disclaimer` to be a primitive type in the JSON string but got " + data['company_disclaimer']);
        }
        // ensure the json data is a string
        if (data['privacy_policy_title'] && !(typeof data['privacy_policy_title'] === 'string' || data['privacy_policy_title'] instanceof String)) {
            throw new Error("Expected the field `privacy_policy_title` to be a primitive type in the JSON string but got " + data['privacy_policy_title']);
        }
        // ensure the json data is a string
        if (data['privacy_policy_content'] && !(typeof data['privacy_policy_content'] === 'string' || data['privacy_policy_content'] instanceof String)) {
            throw new Error("Expected the field `privacy_policy_content` to be a primitive type in the JSON string but got " + data['privacy_policy_content']);
        }
        // ensure the json data is a string
        if (data['privacy_policy_url'] && !(typeof data['privacy_policy_url'] === 'string' || data['privacy_policy_url'] instanceof String)) {
            throw new Error("Expected the field `privacy_policy_url` to be a primitive type in the JSON string but got " + data['privacy_policy_url']);
        }
        // ensure the json data is a string
        if (data['terms_title'] && !(typeof data['terms_title'] === 'string' || data['terms_title'] instanceof String)) {
            throw new Error("Expected the field `terms_title` to be a primitive type in the JSON string but got " + data['terms_title']);
        }
        // ensure the json data is a string
        if (data['terms_content'] && !(typeof data['terms_content'] === 'string' || data['terms_content'] instanceof String)) {
            throw new Error("Expected the field `terms_content` to be a primitive type in the JSON string but got " + data['terms_content']);
        }
        // ensure the json data is a string
        if (data['terms_url'] && !(typeof data['terms_url'] === 'string' || data['terms_url'] instanceof String)) {
            throw new Error("Expected the field `terms_url` to be a primitive type in the JSON string but got " + data['terms_url']);
        }

        return true;
    }


}

LegalSectionRequest.RequiredProperties = ["company_disclaimer", "privacy_policy_url", "terms_url"];

/**
 * @member {String} company_disclaimer
 */
LegalSectionRequest.prototype['company_disclaimer'] = undefined;

/**
 * Short heading title for the privacy policy section
 * @member {String} privacy_policy_title
 */
LegalSectionRequest.prototype['privacy_policy_title'] = undefined;

/**
 * Full content text for the privacy policy section
 * @member {String} privacy_policy_content
 */
LegalSectionRequest.prototype['privacy_policy_content'] = undefined;

/**
 * @member {String} privacy_policy_url
 */
LegalSectionRequest.prototype['privacy_policy_url'] = undefined;

/**
 * Short heading title for the terms and conditions section
 * @member {String} terms_title
 */
LegalSectionRequest.prototype['terms_title'] = undefined;

/**
 * Full content text for the terms and conditions section
 * @member {String} terms_content
 */
LegalSectionRequest.prototype['terms_content'] = undefined;

/**
 * @member {String} terms_url
 */
LegalSectionRequest.prototype['terms_url'] = undefined;






export default LegalSectionRequest;

