/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LegalSection model module.
 * @module model/LegalSection
 * @version 1.0.0
 */
class LegalSection {
    /**
     * Constructs a new <code>LegalSection</code>.
     * Serializer for the LegalSection model. Provides company disclaimer, privacy policy, and terms &amp; conditions information.
     * @alias module:model/LegalSection
     * @param id {Number} 
     * @param companyDisclaimer {String} 
     * @param privacyPolicyUrl {String} 
     * @param termsUrl {String} 
     * @param modifiedAt {Date} 
     * @param modifiedBy {String} 
     */
    constructor(id, companyDisclaimer, privacyPolicyUrl, termsUrl, modifiedAt, modifiedBy) { 
        
        LegalSection.initialize(this, id, companyDisclaimer, privacyPolicyUrl, termsUrl, modifiedAt, modifiedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, companyDisclaimer, privacyPolicyUrl, termsUrl, modifiedAt, modifiedBy) { 
        obj['id'] = id;
        obj['company_disclaimer'] = companyDisclaimer;
        obj['privacy_policy_url'] = privacyPolicyUrl;
        obj['terms_url'] = termsUrl;
        obj['modified_at'] = modifiedAt;
        obj['modified_by'] = modifiedBy;
    }

    /**
     * Constructs a <code>LegalSection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LegalSection} obj Optional instance to populate.
     * @return {module:model/LegalSection} The populated <code>LegalSection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LegalSection();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('company_disclaimer')) {
                obj['company_disclaimer'] = ApiClient.convertToType(data['company_disclaimer'], 'String');
            }
            if (data.hasOwnProperty('privacy_policy_title')) {
                obj['privacy_policy_title'] = ApiClient.convertToType(data['privacy_policy_title'], 'String');
            }
            if (data.hasOwnProperty('privacy_policy_content')) {
                obj['privacy_policy_content'] = ApiClient.convertToType(data['privacy_policy_content'], 'String');
            }
            if (data.hasOwnProperty('privacy_policy_url')) {
                obj['privacy_policy_url'] = ApiClient.convertToType(data['privacy_policy_url'], 'String');
            }
            if (data.hasOwnProperty('terms_title')) {
                obj['terms_title'] = ApiClient.convertToType(data['terms_title'], 'String');
            }
            if (data.hasOwnProperty('terms_content')) {
                obj['terms_content'] = ApiClient.convertToType(data['terms_content'], 'String');
            }
            if (data.hasOwnProperty('terms_url')) {
                obj['terms_url'] = ApiClient.convertToType(data['terms_url'], 'String');
            }
            if (data.hasOwnProperty('modified_at')) {
                obj['modified_at'] = ApiClient.convertToType(data['modified_at'], 'Date');
            }
            if (data.hasOwnProperty('modified_by')) {
                obj['modified_by'] = ApiClient.convertToType(data['modified_by'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LegalSection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LegalSection</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LegalSection.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['company_disclaimer'] && !(typeof data['company_disclaimer'] === 'string' || data['company_disclaimer'] instanceof String)) {
            throw new Error("Expected the field `company_disclaimer` to be a primitive type in the JSON string but got " + data['company_disclaimer']);
        }
        // ensure the json data is a string
        if (data['privacy_policy_title'] && !(typeof data['privacy_policy_title'] === 'string' || data['privacy_policy_title'] instanceof String)) {
            throw new Error("Expected the field `privacy_policy_title` to be a primitive type in the JSON string but got " + data['privacy_policy_title']);
        }
        // ensure the json data is a string
        if (data['privacy_policy_content'] && !(typeof data['privacy_policy_content'] === 'string' || data['privacy_policy_content'] instanceof String)) {
            throw new Error("Expected the field `privacy_policy_content` to be a primitive type in the JSON string but got " + data['privacy_policy_content']);
        }
        // ensure the json data is a string
        if (data['privacy_policy_url'] && !(typeof data['privacy_policy_url'] === 'string' || data['privacy_policy_url'] instanceof String)) {
            throw new Error("Expected the field `privacy_policy_url` to be a primitive type in the JSON string but got " + data['privacy_policy_url']);
        }
        // ensure the json data is a string
        if (data['terms_title'] && !(typeof data['terms_title'] === 'string' || data['terms_title'] instanceof String)) {
            throw new Error("Expected the field `terms_title` to be a primitive type in the JSON string but got " + data['terms_title']);
        }
        // ensure the json data is a string
        if (data['terms_content'] && !(typeof data['terms_content'] === 'string' || data['terms_content'] instanceof String)) {
            throw new Error("Expected the field `terms_content` to be a primitive type in the JSON string but got " + data['terms_content']);
        }
        // ensure the json data is a string
        if (data['terms_url'] && !(typeof data['terms_url'] === 'string' || data['terms_url'] instanceof String)) {
            throw new Error("Expected the field `terms_url` to be a primitive type in the JSON string but got " + data['terms_url']);
        }
        // ensure the json data is a string
        if (data['modified_by'] && !(typeof data['modified_by'] === 'string' || data['modified_by'] instanceof String)) {
            throw new Error("Expected the field `modified_by` to be a primitive type in the JSON string but got " + data['modified_by']);
        }

        return true;
    }


}

LegalSection.RequiredProperties = ["id", "company_disclaimer", "privacy_policy_url", "terms_url", "modified_at", "modified_by"];

/**
 * @member {Number} id
 */
LegalSection.prototype['id'] = undefined;

/**
 * @member {String} company_disclaimer
 */
LegalSection.prototype['company_disclaimer'] = undefined;

/**
 * Short heading title for the privacy policy section
 * @member {String} privacy_policy_title
 */
LegalSection.prototype['privacy_policy_title'] = undefined;

/**
 * Full content text for the privacy policy section
 * @member {String} privacy_policy_content
 */
LegalSection.prototype['privacy_policy_content'] = undefined;

/**
 * @member {String} privacy_policy_url
 */
LegalSection.prototype['privacy_policy_url'] = undefined;

/**
 * Short heading title for the terms and conditions section
 * @member {String} terms_title
 */
LegalSection.prototype['terms_title'] = undefined;

/**
 * Full content text for the terms and conditions section
 * @member {String} terms_content
 */
LegalSection.prototype['terms_content'] = undefined;

/**
 * @member {String} terms_url
 */
LegalSection.prototype['terms_url'] = undefined;

/**
 * @member {Date} modified_at
 */
LegalSection.prototype['modified_at'] = undefined;

/**
 * @member {String} modified_by
 */
LegalSection.prototype['modified_by'] = undefined;






export default LegalSection;

