/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocationOffice model module.
 * @module model/LocationOffice
 * @version 1.0.0
 */
class LocationOffice {
    /**
     * Constructs a new <code>LocationOffice</code>.
     * Serializer for the LocationOffice model. Provides city, address, phone, and is_office information for locations.
     * @alias module:model/LocationOffice
     * @param id {Number} 
     * @param city {String} Name of the city
     * @param modifiedBy {String} 
     */
    constructor(id, city, modifiedBy) { 
        
        LocationOffice.initialize(this, id, city, modifiedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, city, modifiedBy) { 
        obj['id'] = id;
        obj['city'] = city;
        obj['modified_by'] = modifiedBy;
    }

    /**
     * Constructs a <code>LocationOffice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocationOffice} obj Optional instance to populate.
     * @return {module:model/LocationOffice} The populated <code>LocationOffice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocationOffice();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('is_office')) {
                obj['is_office'] = ApiClient.convertToType(data['is_office'], 'Boolean');
            }
            if (data.hasOwnProperty('modified_by')) {
                obj['modified_by'] = ApiClient.convertToType(data['modified_by'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LocationOffice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LocationOffice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LocationOffice.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['modified_by'] && !(typeof data['modified_by'] === 'string' || data['modified_by'] instanceof String)) {
            throw new Error("Expected the field `modified_by` to be a primitive type in the JSON string but got " + data['modified_by']);
        }

        return true;
    }


}

LocationOffice.RequiredProperties = ["id", "city", "modified_by"];

/**
 * @member {Number} id
 */
LocationOffice.prototype['id'] = undefined;

/**
 * Name of the city
 * @member {String} city
 */
LocationOffice.prototype['city'] = undefined;

/**
 * Country name
 * @member {String} country
 */
LocationOffice.prototype['country'] = undefined;

/**
 * Full address of the office
 * @member {String} address
 */
LocationOffice.prototype['address'] = undefined;

/**
 * Office contact number
 * @member {String} phone
 */
LocationOffice.prototype['phone'] = undefined;

/**
 * Office contact email
 * @member {String} email
 */
LocationOffice.prototype['email'] = undefined;

/**
 * Indicates if this is a main office (True) or just a city presence (False)
 * @member {Boolean} is_office
 */
LocationOffice.prototype['is_office'] = undefined;

/**
 * @member {String} modified_by
 */
LocationOffice.prototype['modified_by'] = undefined;






export default LocationOffice;

