/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocationSection model module.
 * @module model/LocationSection
 * @version 1.0.0
 */
class LocationSection {
    /**
     * Constructs a new <code>LocationSection</code>.
     * Serializer for the LocationSection model. Provides main_title and secondary_title for the Locations section in the footer. Includes information about when and by whom it was last modified.
     * @alias module:model/LocationSection
     * @param id {Number} 
     * @param mainTitle {String} The primary title of the Locations section
     * @param secondaryTitle {String} The secondary title for additional context
     * @param modifiedAt {Date} 
     * @param modifiedBy {String} 
     */
    constructor(id, mainTitle, secondaryTitle, modifiedAt, modifiedBy) { 
        
        LocationSection.initialize(this, id, mainTitle, secondaryTitle, modifiedAt, modifiedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, mainTitle, secondaryTitle, modifiedAt, modifiedBy) { 
        obj['id'] = id;
        obj['main_title'] = mainTitle;
        obj['secondary_title'] = secondaryTitle;
        obj['modified_at'] = modifiedAt;
        obj['modified_by'] = modifiedBy;
    }

    /**
     * Constructs a <code>LocationSection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocationSection} obj Optional instance to populate.
     * @return {module:model/LocationSection} The populated <code>LocationSection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocationSection();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('main_title')) {
                obj['main_title'] = ApiClient.convertToType(data['main_title'], 'String');
            }
            if (data.hasOwnProperty('secondary_title')) {
                obj['secondary_title'] = ApiClient.convertToType(data['secondary_title'], 'String');
            }
            if (data.hasOwnProperty('modified_at')) {
                obj['modified_at'] = ApiClient.convertToType(data['modified_at'], 'Date');
            }
            if (data.hasOwnProperty('modified_by')) {
                obj['modified_by'] = ApiClient.convertToType(data['modified_by'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LocationSection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LocationSection</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LocationSection.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['main_title'] && !(typeof data['main_title'] === 'string' || data['main_title'] instanceof String)) {
            throw new Error("Expected the field `main_title` to be a primitive type in the JSON string but got " + data['main_title']);
        }
        // ensure the json data is a string
        if (data['secondary_title'] && !(typeof data['secondary_title'] === 'string' || data['secondary_title'] instanceof String)) {
            throw new Error("Expected the field `secondary_title` to be a primitive type in the JSON string but got " + data['secondary_title']);
        }
        // ensure the json data is a string
        if (data['modified_by'] && !(typeof data['modified_by'] === 'string' || data['modified_by'] instanceof String)) {
            throw new Error("Expected the field `modified_by` to be a primitive type in the JSON string but got " + data['modified_by']);
        }

        return true;
    }


}

LocationSection.RequiredProperties = ["id", "main_title", "secondary_title", "modified_at", "modified_by"];

/**
 * @member {Number} id
 */
LocationSection.prototype['id'] = undefined;

/**
 * The primary title of the Locations section
 * @member {String} main_title
 */
LocationSection.prototype['main_title'] = undefined;

/**
 * The secondary title for additional context
 * @member {String} secondary_title
 */
LocationSection.prototype['secondary_title'] = undefined;

/**
 * @member {Date} modified_at
 */
LocationSection.prototype['modified_at'] = undefined;

/**
 * @member {String} modified_by
 */
LocationSection.prototype['modified_by'] = undefined;






export default LocationSection;

