/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocationSectionRequest model module.
 * @module model/LocationSectionRequest
 * @version 1.0.0
 */
class LocationSectionRequest {
    /**
     * Constructs a new <code>LocationSectionRequest</code>.
     * Serializer for the LocationSection model. Provides main_title and secondary_title for the Locations section in the footer. Includes information about when and by whom it was last modified.
     * @alias module:model/LocationSectionRequest
     * @param mainTitle {String} The primary title of the Locations section
     * @param secondaryTitle {String} The secondary title for additional context
     */
    constructor(mainTitle, secondaryTitle) { 
        
        LocationSectionRequest.initialize(this, mainTitle, secondaryTitle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mainTitle, secondaryTitle) { 
        obj['main_title'] = mainTitle;
        obj['secondary_title'] = secondaryTitle;
    }

    /**
     * Constructs a <code>LocationSectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocationSectionRequest} obj Optional instance to populate.
     * @return {module:model/LocationSectionRequest} The populated <code>LocationSectionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocationSectionRequest();

            if (data.hasOwnProperty('main_title')) {
                obj['main_title'] = ApiClient.convertToType(data['main_title'], 'String');
            }
            if (data.hasOwnProperty('secondary_title')) {
                obj['secondary_title'] = ApiClient.convertToType(data['secondary_title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LocationSectionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LocationSectionRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LocationSectionRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['main_title'] && !(typeof data['main_title'] === 'string' || data['main_title'] instanceof String)) {
            throw new Error("Expected the field `main_title` to be a primitive type in the JSON string but got " + data['main_title']);
        }
        // ensure the json data is a string
        if (data['secondary_title'] && !(typeof data['secondary_title'] === 'string' || data['secondary_title'] instanceof String)) {
            throw new Error("Expected the field `secondary_title` to be a primitive type in the JSON string but got " + data['secondary_title']);
        }

        return true;
    }


}

LocationSectionRequest.RequiredProperties = ["main_title", "secondary_title"];

/**
 * The primary title of the Locations section
 * @member {String} main_title
 */
LocationSectionRequest.prototype['main_title'] = undefined;

/**
 * The secondary title for additional context
 * @member {String} secondary_title
 */
LocationSectionRequest.prototype['secondary_title'] = undefined;






export default LocationSectionRequest;

