/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OperationStatusEnum.
* @enum {}
* @readonly
*/
export default class OperationStatusEnum {
    
        /**
         * value: "open"
         * @const
         */
        "open" = "open";

    
        /**
         * value: "paused"
         * @const
         */
        "paused" = "paused";

    
        /**
         * value: "closed"
         * @const
         */
        "closed" = "closed";

    

    /**
    * Returns a <code>OperationStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OperationStatusEnum} The enum <code>OperationStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

