/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OperationStatusEnum from './OperationStatusEnum';

/**
 * The Operation model module.
 * @module model/Operation
 * @version 1.0.0
 */
class Operation {
    /**
     * Constructs a new <code>Operation</code>.
     * Minimal Operation serializer. Serializador mínimo de Operation.
     * @alias module:model/Operation
     * @param id {Number} 
     * @param name {String} 
     * @param client {Number} 
     * @param region {Number} 
     * @param billingUnit {Number} 
     */
    constructor(id, name, client, region, billingUnit) { 
        
        Operation.initialize(this, id, name, client, region, billingUnit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, client, region, billingUnit) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['client'] = client;
        obj['region'] = region;
        obj['billing_unit'] = billingUnit;
    }

    /**
     * Constructs a <code>Operation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Operation} obj Optional instance to populate.
     * @return {module:model/Operation} The populated <code>Operation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Operation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('client')) {
                obj['client'] = ApiClient.convertToType(data['client'], 'Number');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'Number');
            }
            if (data.hasOwnProperty('billing_unit')) {
                obj['billing_unit'] = ApiClient.convertToType(data['billing_unit'], 'Number');
            }
            if (data.hasOwnProperty('coupe_no')) {
                obj['coupe_no'] = ApiClient.convertToType(data['coupe_no'], 'String');
            }
            if (data.hasOwnProperty('id_info')) {
                obj['id_info'] = ApiClient.convertToType(data['id_info'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = OperationStatusEnum.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Operation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Operation</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Operation.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['coupe_no'] && !(typeof data['coupe_no'] === 'string' || data['coupe_no'] instanceof String)) {
            throw new Error("Expected the field `coupe_no` to be a primitive type in the JSON string but got " + data['coupe_no']);
        }
        // ensure the json data is a string
        if (data['id_info'] && !(typeof data['id_info'] === 'string' || data['id_info'] instanceof String)) {
            throw new Error("Expected the field `id_info` to be a primitive type in the JSON string but got " + data['id_info']);
        }

        return true;
    }


}

Operation.RequiredProperties = ["id", "name", "client", "region", "billing_unit"];

/**
 * @member {Number} id
 */
Operation.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Operation.prototype['name'] = undefined;

/**
 * @member {Number} client
 */
Operation.prototype['client'] = undefined;

/**
 * @member {Number} region
 */
Operation.prototype['region'] = undefined;

/**
 * @member {Number} billing_unit
 */
Operation.prototype['billing_unit'] = undefined;

/**
 * @member {String} coupe_no
 */
Operation.prototype['coupe_no'] = undefined;

/**
 * @member {String} id_info
 */
Operation.prototype['id_info'] = undefined;

/**
 * @member {module:model/OperationStatusEnum} status
 */
Operation.prototype['status'] = undefined;






export default Operation;

