/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrganisationSection model module.
 * @module model/OrganisationSection
 * @version 1.0.0
 */
class OrganisationSection {
    /**
     * Constructs a new <code>OrganisationSection</code>.
     * @alias module:model/OrganisationSection
     * @param id {Number} 
     * @param title {String} Title of the organisation section
     * @param lastModified {Date} 
     * @param modifiedBy {Number} 
     */
    constructor(id, title, lastModified, modifiedBy) { 
        
        OrganisationSection.initialize(this, id, title, lastModified, modifiedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, lastModified, modifiedBy) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['last_modified'] = lastModified;
        obj['modified_by'] = modifiedBy;
    }

    /**
     * Constructs a <code>OrganisationSection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganisationSection} obj Optional instance to populate.
     * @return {module:model/OrganisationSection} The populated <code>OrganisationSection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganisationSection();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('last_modified')) {
                obj['last_modified'] = ApiClient.convertToType(data['last_modified'], 'Date');
            }
            if (data.hasOwnProperty('modified_by')) {
                obj['modified_by'] = ApiClient.convertToType(data['modified_by'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrganisationSection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrganisationSection</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrganisationSection.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

OrganisationSection.RequiredProperties = ["id", "title", "last_modified", "modified_by"];

/**
 * @member {Number} id
 */
OrganisationSection.prototype['id'] = undefined;

/**
 * Title of the organisation section
 * @member {String} title
 */
OrganisationSection.prototype['title'] = undefined;

/**
 * @member {Date} last_modified
 */
OrganisationSection.prototype['last_modified'] = undefined;

/**
 * @member {Number} modified_by
 */
OrganisationSection.prototype['modified_by'] = undefined;






export default OrganisationSection;

