/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProgressEnum from './ProgressEnum';
import Status300Enum from './Status300Enum';

/**
 * The PatchedTimesheetEntryRequest model module.
 * @module model/PatchedTimesheetEntryRequest
 * @version 1.0.0
 */
class PatchedTimesheetEntryRequest {
    /**
     * Constructs a new <code>PatchedTimesheetEntryRequest</code>.
     * Serializer for TimesheetEntry; computed fields are read-only. Serializador para TimesheetEntry; campos calculados son de solo lectura.
     * @alias module:model/PatchedTimesheetEntryRequest
     */
    constructor() { 
        
        PatchedTimesheetEntryRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedTimesheetEntryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedTimesheetEntryRequest} obj Optional instance to populate.
     * @return {module:model/PatchedTimesheetEntryRequest} The populated <code>PatchedTimesheetEntryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedTimesheetEntryRequest();

            if (data.hasOwnProperty('employee')) {
                obj['employee'] = ApiClient.convertToType(data['employee'], 'Number');
            }
            if (data.hasOwnProperty('client')) {
                obj['client'] = ApiClient.convertToType(data['client'], 'Number');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'Number');
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'Number');
            }
            if (data.hasOwnProperty('task')) {
                obj['task'] = ApiClient.convertToType(data['task'], 'Number');
            }
            if (data.hasOwnProperty('work_order')) {
                obj['work_order'] = ApiClient.convertToType(data['work_order'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
            }
            if (data.hasOwnProperty('finish_time')) {
                obj['finish_time'] = ApiClient.convertToType(data['finish_time'], 'String');
            }
            if (data.hasOwnProperty('done')) {
                obj['done'] = ApiClient.convertToType(data['done'], 'Number');
            }
            if (data.hasOwnProperty('progress')) {
                obj['progress'] = ProgressEnum.constructFromObject(data['progress']);
            }
            if (data.hasOwnProperty('risk_assessment')) {
                obj['risk_assessment'] = ApiClient.convertToType(data['risk_assessment'], 'Boolean');
            }
            if (data.hasOwnProperty('hazard_report')) {
                obj['hazard_report'] = ApiClient.convertToType(data['hazard_report'], 'Boolean');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = Status300Enum.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchedTimesheetEntryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchedTimesheetEntryRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['start_time'] && !(typeof data['start_time'] === 'string' || data['start_time'] instanceof String)) {
            throw new Error("Expected the field `start_time` to be a primitive type in the JSON string but got " + data['start_time']);
        }
        // ensure the json data is a string
        if (data['finish_time'] && !(typeof data['finish_time'] === 'string' || data['finish_time'] instanceof String)) {
            throw new Error("Expected the field `finish_time` to be a primitive type in the JSON string but got " + data['finish_time']);
        }
        // ensure the json data is a string
        if (data['done'] && !(typeof data['done'] === 'string' || data['done'] instanceof String)) {
            throw new Error("Expected the field `done` to be a primitive type in the JSON string but got " + data['done']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}



/**
 * @member {Number} employee
 */
PatchedTimesheetEntryRequest.prototype['employee'] = undefined;

/**
 * @member {Number} client
 */
PatchedTimesheetEntryRequest.prototype['client'] = undefined;

/**
 * @member {Number} region
 */
PatchedTimesheetEntryRequest.prototype['region'] = undefined;

/**
 * @member {Number} operation
 */
PatchedTimesheetEntryRequest.prototype['operation'] = undefined;

/**
 * @member {Number} task
 */
PatchedTimesheetEntryRequest.prototype['task'] = undefined;

/**
 * @member {Number} work_order
 */
PatchedTimesheetEntryRequest.prototype['work_order'] = undefined;

/**
 * @member {Date} date
 */
PatchedTimesheetEntryRequest.prototype['date'] = undefined;

/**
 * @member {String} start_time
 */
PatchedTimesheetEntryRequest.prototype['start_time'] = undefined;

/**
 * @member {String} finish_time
 */
PatchedTimesheetEntryRequest.prototype['finish_time'] = undefined;

/**
 * @member {Number} done
 */
PatchedTimesheetEntryRequest.prototype['done'] = undefined;

/**
 * @member {module:model/ProgressEnum} progress
 */
PatchedTimesheetEntryRequest.prototype['progress'] = undefined;

/**
 * @member {Boolean} risk_assessment
 */
PatchedTimesheetEntryRequest.prototype['risk_assessment'] = undefined;

/**
 * @member {Boolean} hazard_report
 */
PatchedTimesheetEntryRequest.prototype['hazard_report'] = undefined;

/**
 * @member {String} notes
 */
PatchedTimesheetEntryRequest.prototype['notes'] = undefined;

/**
 * @member {module:model/Status300Enum} status
 */
PatchedTimesheetEntryRequest.prototype['status'] = undefined;






export default PatchedTimesheetEntryRequest;

