/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedLocationSectionRequest model module.
 * @module model/PatchedLocationSectionRequest
 * @version 1.0.0
 */
class PatchedLocationSectionRequest {
    /**
     * Constructs a new <code>PatchedLocationSectionRequest</code>.
     * Serializer for the LocationSection model. Provides main_title and secondary_title for the Locations section in the footer. Includes information about when and by whom it was last modified.
     * @alias module:model/PatchedLocationSectionRequest
     */
    constructor() { 
        
        PatchedLocationSectionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedLocationSectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedLocationSectionRequest} obj Optional instance to populate.
     * @return {module:model/PatchedLocationSectionRequest} The populated <code>PatchedLocationSectionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedLocationSectionRequest();

            if (data.hasOwnProperty('main_title')) {
                obj['main_title'] = ApiClient.convertToType(data['main_title'], 'String');
            }
            if (data.hasOwnProperty('secondary_title')) {
                obj['secondary_title'] = ApiClient.convertToType(data['secondary_title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchedLocationSectionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchedLocationSectionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['main_title'] && !(typeof data['main_title'] === 'string' || data['main_title'] instanceof String)) {
            throw new Error("Expected the field `main_title` to be a primitive type in the JSON string but got " + data['main_title']);
        }
        // ensure the json data is a string
        if (data['secondary_title'] && !(typeof data['secondary_title'] === 'string' || data['secondary_title'] instanceof String)) {
            throw new Error("Expected the field `secondary_title` to be a primitive type in the JSON string but got " + data['secondary_title']);
        }

        return true;
    }


}



/**
 * The primary title of the Locations section
 * @member {String} main_title
 */
PatchedLocationSectionRequest.prototype['main_title'] = undefined;

/**
 * The secondary title for additional context
 * @member {String} secondary_title
 */
PatchedLocationSectionRequest.prototype['secondary_title'] = undefined;






export default PatchedLocationSectionRequest;

