/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedWorkOrderRequest model module.
 * @module model/PatchedWorkOrderRequest
 * @version 1.0.0
 */
class PatchedWorkOrderRequest {
    /**
     * Constructs a new <code>PatchedWorkOrderRequest</code>.
     * Minimal WorkOrder serializer. Serializador mínimo de WorkOrder.
     * @alias module:model/PatchedWorkOrderRequest
     */
    constructor() { 
        
        PatchedWorkOrderRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['active'] = true;
    }

    /**
     * Constructs a <code>PatchedWorkOrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedWorkOrderRequest} obj Optional instance to populate.
     * @return {module:model/PatchedWorkOrderRequest} The populated <code>PatchedWorkOrderRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedWorkOrderRequest();

            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'Number');
            }
            if (data.hasOwnProperty('coupe_no')) {
                obj['coupe_no'] = ApiClient.convertToType(data['coupe_no'], 'String');
            }
            if (data.hasOwnProperty('id_info')) {
                obj['id_info'] = ApiClient.convertToType(data['id_info'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchedWorkOrderRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchedWorkOrderRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['coupe_no'] && !(typeof data['coupe_no'] === 'string' || data['coupe_no'] instanceof String)) {
            throw new Error("Expected the field `coupe_no` to be a primitive type in the JSON string but got " + data['coupe_no']);
        }
        // ensure the json data is a string
        if (data['id_info'] && !(typeof data['id_info'] === 'string' || data['id_info'] instanceof String)) {
            throw new Error("Expected the field `id_info` to be a primitive type in the JSON string but got " + data['id_info']);
        }

        return true;
    }


}



/**
 * @member {Number} operation
 */
PatchedWorkOrderRequest.prototype['operation'] = undefined;

/**
 * @member {String} coupe_no
 */
PatchedWorkOrderRequest.prototype['coupe_no'] = undefined;

/**
 * @member {String} id_info
 */
PatchedWorkOrderRequest.prototype['id_info'] = undefined;

/**
 * @member {Date} start_date
 */
PatchedWorkOrderRequest.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
PatchedWorkOrderRequest.prototype['end_date'] = undefined;

/**
 * @member {Boolean} active
 * @default true
 */
PatchedWorkOrderRequest.prototype['active'] = true;






export default PatchedWorkOrderRequest;

