/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedEmployeeRequest model module.
 * @module model/PatchedEmployeeRequest
 * @version 1.0.0
 */
class PatchedEmployeeRequest {
    /**
     * Constructs a new <code>PatchedEmployeeRequest</code>.
     * Basic Employee serializer. Serializador básico de Employee.
     * @alias module:model/PatchedEmployeeRequest
     */
    constructor() { 
        
        PatchedEmployeeRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedEmployeeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedEmployeeRequest} obj Optional instance to populate.
     * @return {module:model/PatchedEmployeeRequest} The populated <code>PatchedEmployeeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedEmployeeRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchedEmployeeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchedEmployeeRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
PatchedEmployeeRequest.prototype['name'] = undefined;

/**
 * @member {Boolean} active
 */
PatchedEmployeeRequest.prototype['active'] = undefined;

/**
 * Link to auth user for login/permissions; optional. / Enlace al usuario auth para login/permisos; opcional.
 * @member {Number} user
 */
PatchedEmployeeRequest.prototype['user'] = undefined;






export default PatchedEmployeeRequest;

