/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PlatformNameEnum.
* @enum {}
* @readonly
*/
export default class PlatformNameEnum {
    
        /**
         * value: "facebook"
         * @const
         */
        "facebook" = "facebook";

    
        /**
         * value: "twitter"
         * @const
         */
        "twitter" = "twitter";

    
        /**
         * value: "linkedin"
         * @const
         */
        "linkedin" = "linkedin";

    
        /**
         * value: "instagram"
         * @const
         */
        "instagram" = "instagram";

    
        /**
         * value: "youtube"
         * @const
         */
        "youtube" = "youtube";

    
        /**
         * value: "tiktok"
         * @const
         */
        "tiktok" = "tiktok";

    
        /**
         * value: "github"
         * @const
         */
        "github" = "github";

    
        /**
         * value: "discord"
         * @const
         */
        "discord" = "discord";

    
        /**
         * value: "threads"
         * @const
         */
        "threads" = "threads";

    
        /**
         * value: "mastodon"
         * @const
         */
        "mastodon" = "mastodon";

    
        /**
         * value: "snapchat"
         * @const
         */
        "snapchat" = "snapchat";

    
        /**
         * value: "reddit"
         * @const
         */
        "reddit" = "reddit";

    
        /**
         * value: "pinterest"
         * @const
         */
        "pinterest" = "pinterest";

    
        /**
         * value: "whatsapp"
         * @const
         */
        "whatsapp" = "whatsapp";

    
        /**
         * value: "telegram"
         * @const
         */
        "telegram" = "telegram";

    
        /**
         * value: "other"
         * @const
         */
        "other" = "other";

    

    /**
    * Returns a <code>PlatformNameEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PlatformNameEnum} The enum <code>PlatformNameEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

