/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuickNote model module.
 * @module model/QuickNote
 * @version 1.0.0
 */
class QuickNote {
    /**
     * Constructs a new <code>QuickNote</code>.
     * Minimal QuickNote serializer scoped by region. Serializador mínimo de QuickNote acotado por región.
     * @alias module:model/QuickNote
     * @param id {Number} 
     * @param label {String} 
     * @param region {Number} 
     */
    constructor(id, label, region) { 
        
        QuickNote.initialize(this, id, label, region);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, label, region) { 
        obj['id'] = id;
        obj['label'] = label;
        obj['region'] = region;
    }

    /**
     * Constructs a <code>QuickNote</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuickNote} obj Optional instance to populate.
     * @return {module:model/QuickNote} The populated <code>QuickNote</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuickNote();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuickNote</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuickNote</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuickNote.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }

        return true;
    }


}

QuickNote.RequiredProperties = ["id", "label", "region"];

/**
 * @member {Number} id
 */
QuickNote.prototype['id'] = undefined;

/**
 * @member {String} label
 */
QuickNote.prototype['label'] = undefined;

/**
 * @member {Number} region
 */
QuickNote.prototype['region'] = undefined;






export default QuickNote;

