/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Image from './Image';

/**
 * The Section model module.
 * @module model/Section
 * @version 1.0.0
 */
class Section {
    /**
     * Constructs a new <code>Section</code>.
     * @alias module:model/Section
     * @param id {Number} 
     * @param title {String} 
     * @param slug {String} 
     * @param content {String} 
     * @param images {Array.<module:model/Image>} 
     */
    constructor(id, title, slug, content, images) { 
        
        Section.initialize(this, id, title, slug, content, images);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, slug, content, images) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['slug'] = slug;
        obj['content'] = content;
        obj['images'] = images;
    }

    /**
     * Constructs a <code>Section</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Section} obj Optional instance to populate.
     * @return {module:model/Section} The populated <code>Section</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Section();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [Image]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Section</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Section</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Section.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        if (data['images']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['images'])) {
                throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
            }
            // validate the optional field `images` (array)
            for (const item of data['images']) {
                Image.validateJSON(item);
            };
        }

        return true;
    }


}

Section.RequiredProperties = ["id", "title", "slug", "content", "images"];

/**
 * @member {Number} id
 */
Section.prototype['id'] = undefined;

/**
 * @member {String} title
 */
Section.prototype['title'] = undefined;

/**
 * @member {String} slug
 */
Section.prototype['slug'] = undefined;

/**
 * @member {String} content
 */
Section.prototype['content'] = undefined;

/**
 * @member {Number} order
 */
Section.prototype['order'] = undefined;

/**
 * @member {Array.<module:model/Image>} images
 */
Section.prototype['images'] = undefined;






export default Section;

