/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlatformNameEnum from './PlatformNameEnum';

/**
 * The SocialMedia model module.
 * @module model/SocialMedia
 * @version 1.0.0
 */
class SocialMedia {
    /**
     * Constructs a new <code>SocialMedia</code>.
     * Serializer for the SocialMedia model. Provides platform name, profile URL, and other details for social media links. Includes validation to ensure custom_name is provided when \&quot;other\&quot; platform is selected.
     * @alias module:model/SocialMedia
     * @param id {Number} 
     * @param platformName {module:model/PlatformNameEnum} Select the social media platform  * `facebook` - Facebook * `twitter` - Twitter * `linkedin` - LinkedIn * `instagram` - Instagram * `youtube` - YouTube * `tiktok` - TikTok * `github` - GitHub * `discord` - Discord * `threads` - Threads * `mastodon` - Mastodon * `snapchat` - Snapchat * `reddit` - Reddit * `pinterest` - Pinterest * `whatsapp` - WhatsApp * `telegram` - Telegram * `other` - Other (Specify Below)
     * @param platformDisplayName {String} 
     * @param profileUrl {String} URL to the company's social media profile
     * @param modifiedAt {Date} 
     * @param modifiedBy {String} 
     */
    constructor(id, platformName, platformDisplayName, profileUrl, modifiedAt, modifiedBy) { 
        
        SocialMedia.initialize(this, id, platformName, platformDisplayName, profileUrl, modifiedAt, modifiedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, platformName, platformDisplayName, profileUrl, modifiedAt, modifiedBy) { 
        obj['id'] = id;
        obj['platform_name'] = platformName;
        obj['platform_display_name'] = platformDisplayName;
        obj['profile_url'] = profileUrl;
        obj['modified_at'] = modifiedAt;
        obj['modified_by'] = modifiedBy;
    }

    /**
     * Constructs a <code>SocialMedia</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SocialMedia} obj Optional instance to populate.
     * @return {module:model/SocialMedia} The populated <code>SocialMedia</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SocialMedia();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('platform_name')) {
                obj['platform_name'] = ApiClient.convertToType(data['platform_name'], PlatformNameEnum);
            }
            if (data.hasOwnProperty('platform_display_name')) {
                obj['platform_display_name'] = ApiClient.convertToType(data['platform_display_name'], 'String');
            }
            if (data.hasOwnProperty('custom_name')) {
                obj['custom_name'] = ApiClient.convertToType(data['custom_name'], 'String');
            }
            if (data.hasOwnProperty('profile_url')) {
                obj['profile_url'] = ApiClient.convertToType(data['profile_url'], 'String');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('modified_at')) {
                obj['modified_at'] = ApiClient.convertToType(data['modified_at'], 'Date');
            }
            if (data.hasOwnProperty('modified_by')) {
                obj['modified_by'] = ApiClient.convertToType(data['modified_by'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SocialMedia</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SocialMedia</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SocialMedia.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['platform_display_name'] && !(typeof data['platform_display_name'] === 'string' || data['platform_display_name'] instanceof String)) {
            throw new Error("Expected the field `platform_display_name` to be a primitive type in the JSON string but got " + data['platform_display_name']);
        }
        // ensure the json data is a string
        if (data['custom_name'] && !(typeof data['custom_name'] === 'string' || data['custom_name'] instanceof String)) {
            throw new Error("Expected the field `custom_name` to be a primitive type in the JSON string but got " + data['custom_name']);
        }
        // ensure the json data is a string
        if (data['profile_url'] && !(typeof data['profile_url'] === 'string' || data['profile_url'] instanceof String)) {
            throw new Error("Expected the field `profile_url` to be a primitive type in the JSON string but got " + data['profile_url']);
        }
        // ensure the json data is a string
        if (data['modified_by'] && !(typeof data['modified_by'] === 'string' || data['modified_by'] instanceof String)) {
            throw new Error("Expected the field `modified_by` to be a primitive type in the JSON string but got " + data['modified_by']);
        }

        return true;
    }


}

SocialMedia.RequiredProperties = ["id", "platform_name", "platform_display_name", "profile_url", "modified_at", "modified_by"];

/**
 * @member {Number} id
 */
SocialMedia.prototype['id'] = undefined;

/**
 * Select the social media platform  * `facebook` - Facebook * `twitter` - Twitter * `linkedin` - LinkedIn * `instagram` - Instagram * `youtube` - YouTube * `tiktok` - TikTok * `github` - GitHub * `discord` - Discord * `threads` - Threads * `mastodon` - Mastodon * `snapchat` - Snapchat * `reddit` - Reddit * `pinterest` - Pinterest * `whatsapp` - WhatsApp * `telegram` - Telegram * `other` - Other (Specify Below)
 * @member {module:model/PlatformNameEnum} platform_name
 */
SocialMedia.prototype['platform_name'] = undefined;

/**
 * @member {String} platform_display_name
 */
SocialMedia.prototype['platform_display_name'] = undefined;

/**
 * Specify the platform name if 'Other' is selected
 * @member {String} custom_name
 */
SocialMedia.prototype['custom_name'] = undefined;

/**
 * URL to the company's social media profile
 * @member {String} profile_url
 */
SocialMedia.prototype['profile_url'] = undefined;

/**
 * Whether this social media link is active and should be displayed
 * @member {Boolean} is_active
 */
SocialMedia.prototype['is_active'] = undefined;

/**
 * @member {Date} modified_at
 */
SocialMedia.prototype['modified_at'] = undefined;

/**
 * @member {String} modified_by
 */
SocialMedia.prototype['modified_by'] = undefined;






export default SocialMedia;

