/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Status300Enum.
* @enum {}
* @readonly
*/
export default class Status300Enum {
    
        /**
         * value: "draft"
         * @const
         */
        "draft" = "draft";

    
        /**
         * value: "submitted"
         * @const
         */
        "submitted" = "submitted";

    
        /**
         * value: "approved"
         * @const
         */
        "approved" = "approved";

    
        /**
         * value: "locked"
         * @const
         */
        "locked" = "locked";

    

    /**
    * Returns a <code>Status300Enum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Status300Enum} The enum <code>Status300Enum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

