/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status300Enum from './Status300Enum';

/**
 * The TimesheetSubmission model module.
 * @module model/TimesheetSubmission
 * @version 1.0.0
 */
class TimesheetSubmission {
    /**
     * Constructs a new <code>TimesheetSubmission</code>.
     * Basic serializer for TimesheetSubmission objects. Serializador básico para TimesheetSubmission.
     * @alias module:model/TimesheetSubmission
     * @param id {Number} 
     * @param employee {Number} 
     * @param periodStart {Date} 
     * @param periodEnd {Date} 
     * @param status {module:model/Status300Enum} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, employee, periodStart, periodEnd, status, createdAt, updatedAt) { 
        
        TimesheetSubmission.initialize(this, id, employee, periodStart, periodEnd, status, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, employee, periodStart, periodEnd, status, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['employee'] = employee;
        obj['period_start'] = periodStart;
        obj['period_end'] = periodEnd;
        obj['status'] = status;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>TimesheetSubmission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimesheetSubmission} obj Optional instance to populate.
     * @return {module:model/TimesheetSubmission} The populated <code>TimesheetSubmission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimesheetSubmission();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('employee')) {
                obj['employee'] = ApiClient.convertToType(data['employee'], 'Number');
            }
            if (data.hasOwnProperty('period_start')) {
                obj['period_start'] = ApiClient.convertToType(data['period_start'], 'Date');
            }
            if (data.hasOwnProperty('period_end')) {
                obj['period_end'] = ApiClient.convertToType(data['period_end'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], Status300Enum);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TimesheetSubmission</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TimesheetSubmission</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TimesheetSubmission.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

TimesheetSubmission.RequiredProperties = ["id", "employee", "period_start", "period_end", "status", "created_at", "updated_at"];

/**
 * @member {Number} id
 */
TimesheetSubmission.prototype['id'] = undefined;

/**
 * @member {Number} employee
 */
TimesheetSubmission.prototype['employee'] = undefined;

/**
 * @member {Date} period_start
 */
TimesheetSubmission.prototype['period_start'] = undefined;

/**
 * @member {Date} period_end
 */
TimesheetSubmission.prototype['period_end'] = undefined;

/**
 * @member {module:model/Status300Enum} status
 */
TimesheetSubmission.prototype['status'] = undefined;

/**
 * @member {Date} created_at
 */
TimesheetSubmission.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
TimesheetSubmission.prototype['updated_at'] = undefined;






export default TimesheetSubmission;

