/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TimesheetSubmissionRequest model module.
 * @module model/TimesheetSubmissionRequest
 * @version 1.0.0
 */
class TimesheetSubmissionRequest {
    /**
     * Constructs a new <code>TimesheetSubmissionRequest</code>.
     * Basic serializer for TimesheetSubmission objects. Serializador básico para TimesheetSubmission.
     * @alias module:model/TimesheetSubmissionRequest
     * @param employee {Number} 
     * @param periodStart {Date} 
     * @param periodEnd {Date} 
     */
    constructor(employee, periodStart, periodEnd) { 
        
        TimesheetSubmissionRequest.initialize(this, employee, periodStart, periodEnd);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, employee, periodStart, periodEnd) { 
        obj['employee'] = employee;
        obj['period_start'] = periodStart;
        obj['period_end'] = periodEnd;
    }

    /**
     * Constructs a <code>TimesheetSubmissionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimesheetSubmissionRequest} obj Optional instance to populate.
     * @return {module:model/TimesheetSubmissionRequest} The populated <code>TimesheetSubmissionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimesheetSubmissionRequest();

            if (data.hasOwnProperty('employee')) {
                obj['employee'] = ApiClient.convertToType(data['employee'], 'Number');
            }
            if (data.hasOwnProperty('period_start')) {
                obj['period_start'] = ApiClient.convertToType(data['period_start'], 'Date');
            }
            if (data.hasOwnProperty('period_end')) {
                obj['period_end'] = ApiClient.convertToType(data['period_end'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TimesheetSubmissionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TimesheetSubmissionRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TimesheetSubmissionRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

TimesheetSubmissionRequest.RequiredProperties = ["employee", "period_start", "period_end"];

/**
 * @member {Number} employee
 */
TimesheetSubmissionRequest.prototype['employee'] = undefined;

/**
 * @member {Date} period_start
 */
TimesheetSubmissionRequest.prototype['period_start'] = undefined;

/**
 * @member {Date} period_end
 */
TimesheetSubmissionRequest.prototype['period_end'] = undefined;






export default TimesheetSubmissionRequest;

