/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkOrder model module.
 * @module model/WorkOrder
 * @version 1.0.0
 */
class WorkOrder {
    /**
     * Constructs a new <code>WorkOrder</code>.
     * Minimal WorkOrder serializer. Serializador mínimo de WorkOrder.
     * @alias module:model/WorkOrder
     * @param id {Number} 
     * @param operation {Number} 
     * @param coupeNo {String} 
     * @param idInfo {String} 
     */
    constructor(id, operation, coupeNo, idInfo) { 
        
        WorkOrder.initialize(this, id, operation, coupeNo, idInfo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, operation, coupeNo, idInfo) { 
        obj['id'] = id;
        obj['operation'] = operation;
        obj['coupe_no'] = coupeNo;
        obj['id_info'] = idInfo;
        obj['active'] = true;
    }

    /**
     * Constructs a <code>WorkOrder</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkOrder} obj Optional instance to populate.
     * @return {module:model/WorkOrder} The populated <code>WorkOrder</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkOrder();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'Number');
            }
            if (data.hasOwnProperty('coupe_no')) {
                obj['coupe_no'] = ApiClient.convertToType(data['coupe_no'], 'String');
            }
            if (data.hasOwnProperty('id_info')) {
                obj['id_info'] = ApiClient.convertToType(data['id_info'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkOrder</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkOrder</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkOrder.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['coupe_no'] && !(typeof data['coupe_no'] === 'string' || data['coupe_no'] instanceof String)) {
            throw new Error("Expected the field `coupe_no` to be a primitive type in the JSON string but got " + data['coupe_no']);
        }
        // ensure the json data is a string
        if (data['id_info'] && !(typeof data['id_info'] === 'string' || data['id_info'] instanceof String)) {
            throw new Error("Expected the field `id_info` to be a primitive type in the JSON string but got " + data['id_info']);
        }

        return true;
    }


}

WorkOrder.RequiredProperties = ["id", "operation", "coupe_no", "id_info"];

/**
 * @member {Number} id
 */
WorkOrder.prototype['id'] = undefined;

/**
 * @member {Number} operation
 */
WorkOrder.prototype['operation'] = undefined;

/**
 * @member {String} coupe_no
 */
WorkOrder.prototype['coupe_no'] = undefined;

/**
 * @member {String} id_info
 */
WorkOrder.prototype['id_info'] = undefined;

/**
 * @member {Date} start_date
 */
WorkOrder.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
WorkOrder.prototype['end_date'] = undefined;

/**
 * @member {Boolean} active
 * @default true
 */
WorkOrder.prototype['active'] = true;






export default WorkOrder;

