/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.PatchedLocationSectionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PatchedLocationSectionRequest', function() {
    it('should create an instance of PatchedLocationSectionRequest', function() {
      // uncomment below and update the code to test PatchedLocationSectionRequest
      //var instance = new TimesheetApi.PatchedLocationSectionRequest();
      //expect(instance).to.be.a(TimesheetApi.PatchedLocationSectionRequest);
    });

    it('should have the property mainTitle (base name: "main_title")', function() {
      // uncomment below and update the code to test the property mainTitle
      //var instance = new TimesheetApi.PatchedLocationSectionRequest();
      //expect(instance).to.be();
    });

    it('should have the property secondaryTitle (base name: "secondary_title")', function() {
      // uncomment below and update the code to test the property secondaryTitle
      //var instance = new TimesheetApi.PatchedLocationSectionRequest();
      //expect(instance).to.be();
    });

  });

}));
