/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TimesheetApi);
  }
}(this, function(expect, TimesheetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TimesheetApi.TimesheetSubmission();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TimesheetSubmission', function() {
    it('should create an instance of TimesheetSubmission', function() {
      // uncomment below and update the code to test TimesheetSubmission
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be.a(TimesheetApi.TimesheetSubmission);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be();
    });

    it('should have the property employee (base name: "employee")', function() {
      // uncomment below and update the code to test the property employee
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be();
    });

    it('should have the property periodStart (base name: "period_start")', function() {
      // uncomment below and update the code to test the property periodStart
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be();
    });

    it('should have the property periodEnd (base name: "period_end")', function() {
      // uncomment below and update the code to test the property periodEnd
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new TimesheetApi.TimesheetSubmission();
      //expect(instance).to.be();
    });

  });

}));
