/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BillingUnit from '../model/BillingUnit';
import BillingUnitRequest from '../model/BillingUnitRequest';
import PaginatedBillingUnitList from '../model/PaginatedBillingUnitList';
import PatchedBillingUnitRequest from '../model/PatchedBillingUnitRequest';

/**
* BillingUnit service.
* @module api/BillingUnitApi
* @version 1.0.0
*/
export default class BillingUnitApi {

    /**
    * Constructs a new BillingUnitApi. 
    * @alias module:api/BillingUnitApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/BillingUnitRequest} billingUnitRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BillingUnit} and HTTP response
     */
    billingUnitsCreateWithHttpInfo(billingUnitRequest) {
      let postBody = billingUnitRequest;
      // verify the required parameter 'billingUnitRequest' is set
      if (billingUnitRequest === undefined || billingUnitRequest === null) {
        throw new Error("Missing the required parameter 'billingUnitRequest' when calling billingUnitsCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = BillingUnit;
      return this.apiClient.callApi(
        '/api/billing-units/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/BillingUnitRequest} billingUnitRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BillingUnit}
     */
    billingUnitsCreate(billingUnitRequest) {
      return this.billingUnitsCreateWithHttpInfo(billingUnitRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    billingUnitsDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling billingUnitsDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/billing-units/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    billingUnitsDestroy(id) {
      return this.billingUnitsDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedBillingUnitList} and HTTP response
     */
    billingUnitsListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedBillingUnitList;
      return this.apiClient.callApi(
        '/api/billing-units/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedBillingUnitList}
     */
    billingUnitsList(opts) {
      return this.billingUnitsListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedBillingUnitRequest} [patchedBillingUnitRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BillingUnit} and HTTP response
     */
    billingUnitsPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedBillingUnitRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling billingUnitsPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = BillingUnit;
      return this.apiClient.callApi(
        '/api/billing-units/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedBillingUnitRequest} opts.patchedBillingUnitRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BillingUnit}
     */
    billingUnitsPartialUpdate(id, opts) {
      return this.billingUnitsPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BillingUnit} and HTTP response
     */
    billingUnitsRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling billingUnitsRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingUnit;
      return this.apiClient.callApi(
        '/api/billing-units/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BillingUnit}
     */
    billingUnitsRetrieve(id) {
      return this.billingUnitsRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @param {module:model/BillingUnitRequest} billingUnitRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BillingUnit} and HTTP response
     */
    billingUnitsUpdateWithHttpInfo(id, billingUnitRequest) {
      let postBody = billingUnitRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling billingUnitsUpdate");
      }
      // verify the required parameter 'billingUnitRequest' is set
      if (billingUnitRequest === undefined || billingUnitRequest === null) {
        throw new Error("Missing the required parameter 'billingUnitRequest' when calling billingUnitsUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = BillingUnit;
      return this.apiClient.callApi(
        '/api/billing-units/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this Billing Unit.
     * @param {module:model/BillingUnitRequest} billingUnitRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BillingUnit}
     */
    billingUnitsUpdate(id, billingUnitRequest) {
      return this.billingUnitsUpdateWithHttpInfo(id, billingUnitRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
