/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Client from '../model/Client';
import ClientRequest from '../model/ClientRequest';
import PaginatedClientList from '../model/PaginatedClientList';
import PatchedClientRequest from '../model/PatchedClientRequest';

/**
* Client service.
* @module api/ClientApi
* @version 1.0.0
*/
export default class ClientApi {

    /**
    * Constructs a new ClientApi. 
    * @alias module:api/ClientApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/ClientRequest} clientRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Client} and HTTP response
     */
    clientsCreateWithHttpInfo(clientRequest) {
      let postBody = clientRequest;
      // verify the required parameter 'clientRequest' is set
      if (clientRequest === undefined || clientRequest === null) {
        throw new Error("Missing the required parameter 'clientRequest' when calling clientsCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Client;
      return this.apiClient.callApi(
        '/api/clients/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/ClientRequest} clientRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Client}
     */
    clientsCreate(clientRequest) {
      return this.clientsCreateWithHttpInfo(clientRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    clientsDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling clientsDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/clients/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    clientsDestroy(id) {
      return this.clientsDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedClientList} and HTTP response
     */
    clientsListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedClientList;
      return this.apiClient.callApi(
        '/api/clients/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedClientList}
     */
    clientsList(opts) {
      return this.clientsListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedClientRequest} [patchedClientRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Client} and HTTP response
     */
    clientsPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedClientRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling clientsPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Client;
      return this.apiClient.callApi(
        '/api/clients/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedClientRequest} opts.patchedClientRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Client}
     */
    clientsPartialUpdate(id, opts) {
      return this.clientsPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Client} and HTTP response
     */
    clientsRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling clientsRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Client;
      return this.apiClient.callApi(
        '/api/clients/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Client}
     */
    clientsRetrieve(id) {
      return this.clientsRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @param {module:model/ClientRequest} clientRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Client} and HTTP response
     */
    clientsUpdateWithHttpInfo(id, clientRequest) {
      let postBody = clientRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling clientsUpdate");
      }
      // verify the required parameter 'clientRequest' is set
      if (clientRequest === undefined || clientRequest === null) {
        throw new Error("Missing the required parameter 'clientRequest' when calling clientsUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Client;
      return this.apiClient.callApi(
        '/api/clients/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Client.
     * @param {module:model/ClientRequest} clientRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Client}
     */
    clientsUpdate(id, clientRequest) {
      return this.clientsUpdateWithHttpInfo(id, clientRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
