/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ContactMessage from '../model/ContactMessage';
import ContactMessageRequest from '../model/ContactMessageRequest';

/**
* Contact service.
* @module api/ContactApi
* @version 1.0.0
*/
export default class ContactApi {

    /**
    * Constructs a new ContactApi. 
    * @alias module:api/ContactApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * API endpoint that allows users to submit contact form messages.  This endpoint accepts POST requests with name, email, and message fields. No authentication is required to submit a contact message. Upon successful submission, an email is sent to the configured recipient.
     * @param {module:model/ContactMessageRequest} contactMessageRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ContactMessage} and HTTP response
     */
    contactCreateWithHttpInfo(contactMessageRequest) {
      let postBody = contactMessageRequest;
      // verify the required parameter 'contactMessageRequest' is set
      if (contactMessageRequest === undefined || contactMessageRequest === null) {
        throw new Error("Missing the required parameter 'contactMessageRequest' when calling contactCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = ContactMessage;
      return this.apiClient.callApi(
        '/api/contact/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint that allows users to submit contact form messages.  This endpoint accepts POST requests with name, email, and message fields. No authentication is required to submit a contact message. Upon successful submission, an email is sent to the configured recipient.
     * @param {module:model/ContactMessageRequest} contactMessageRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ContactMessage}
     */
    contactCreate(contactMessageRequest) {
      return this.contactCreateWithHttpInfo(contactMessageRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
