/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* FooterCta service.
* @module api/FooterCtaApi
* @version 1.0.0
*/
export default class FooterCtaApi {

    /**
    * Constructs a new FooterCtaApi. 
    * @alias module:api/FooterCtaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * API endpoint that returns the Footer Call-To-Action data. Returns the latest CTA information including title, description, button text, and contact person details (name, position, and phone number).
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    footerCtaRetrieveWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/footer-cta/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint that returns the Footer Call-To-Action data. Returns the latest CTA information including title, description, button text, and contact person details (name, position, and phone number).
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    footerCtaRetrieve() {
      return this.footerCtaRetrieveWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
