/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LeaveEntry from '../model/LeaveEntry';
import LeaveEntryRequest from '../model/LeaveEntryRequest';
import PaginatedLeaveEntryList from '../model/PaginatedLeaveEntryList';
import PatchedLeaveEntryRequest from '../model/PatchedLeaveEntryRequest';

/**
* LeaveEntry service.
* @module api/LeaveEntryApi
* @version 1.0.0
*/
export default class LeaveEntryApi {

    /**
    * Constructs a new LeaveEntryApi. 
    * @alias module:api/LeaveEntryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/LeaveEntryRequest} leaveEntryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LeaveEntry} and HTTP response
     */
    leaveEntriesCreateWithHttpInfo(leaveEntryRequest) {
      let postBody = leaveEntryRequest;
      // verify the required parameter 'leaveEntryRequest' is set
      if (leaveEntryRequest === undefined || leaveEntryRequest === null) {
        throw new Error("Missing the required parameter 'leaveEntryRequest' when calling leaveEntriesCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LeaveEntry;
      return this.apiClient.callApi(
        '/api/leave-entries/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/LeaveEntryRequest} leaveEntryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LeaveEntry}
     */
    leaveEntriesCreate(leaveEntryRequest) {
      return this.leaveEntriesCreateWithHttpInfo(leaveEntryRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    leaveEntriesDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling leaveEntriesDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/leave-entries/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    leaveEntriesDestroy(id) {
      return this.leaveEntriesDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedLeaveEntryList} and HTTP response
     */
    leaveEntriesListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedLeaveEntryList;
      return this.apiClient.callApi(
        '/api/leave-entries/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedLeaveEntryList}
     */
    leaveEntriesList(opts) {
      return this.leaveEntriesListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedLeaveEntryRequest} [patchedLeaveEntryRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LeaveEntry} and HTTP response
     */
    leaveEntriesPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedLeaveEntryRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling leaveEntriesPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LeaveEntry;
      return this.apiClient.callApi(
        '/api/leave-entries/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedLeaveEntryRequest} opts.patchedLeaveEntryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LeaveEntry}
     */
    leaveEntriesPartialUpdate(id, opts) {
      return this.leaveEntriesPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LeaveEntry} and HTTP response
     */
    leaveEntriesRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling leaveEntriesRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LeaveEntry;
      return this.apiClient.callApi(
        '/api/leave-entries/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LeaveEntry}
     */
    leaveEntriesRetrieve(id) {
      return this.leaveEntriesRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @param {module:model/LeaveEntryRequest} leaveEntryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LeaveEntry} and HTTP response
     */
    leaveEntriesUpdateWithHttpInfo(id, leaveEntryRequest) {
      let postBody = leaveEntryRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling leaveEntriesUpdate");
      }
      // verify the required parameter 'leaveEntryRequest' is set
      if (leaveEntryRequest === undefined || leaveEntryRequest === null) {
        throw new Error("Missing the required parameter 'leaveEntryRequest' when calling leaveEntriesUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LeaveEntry;
      return this.apiClient.callApi(
        '/api/leave-entries/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} id A unique integer value identifying this leave entry.
     * @param {module:model/LeaveEntryRequest} leaveEntryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LeaveEntry}
     */
    leaveEntriesUpdate(id, leaveEntryRequest) {
      return this.leaveEntriesUpdateWithHttpInfo(id, leaveEntryRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
