/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LegalSection from '../model/LegalSection';
import LegalSectionRequest from '../model/LegalSectionRequest';
import PatchedLegalSectionRequest from '../model/PatchedLegalSectionRequest';

/**
* LegalSection service.
* @module api/LegalSectionApi
* @version 1.0.0
*/
export default class LegalSectionApi {

    /**
    * Constructs a new LegalSectionApi. 
    * @alias module:api/LegalSectionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * API endpoint for managing legal information in the footer. Supports GET, PUT, and PATCH operations to retrieve or update the legal information. Only one instance of this model exists.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedLegalSectionRequest} [patchedLegalSectionRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LegalSection} and HTTP response
     */
    legalSectionPartialUpdateWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['patchedLegalSectionRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LegalSection;
      return this.apiClient.callApi(
        '/api/legal-section/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint for managing legal information in the footer. Supports GET, PUT, and PATCH operations to retrieve or update the legal information. Only one instance of this model exists.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedLegalSectionRequest} opts.patchedLegalSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LegalSection}
     */
    legalSectionPartialUpdate(opts) {
      return this.legalSectionPartialUpdateWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API endpoint for managing legal information in the footer. Supports GET, PUT, and PATCH operations to retrieve or update the legal information. Only one instance of this model exists.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LegalSection} and HTTP response
     */
    legalSectionRetrieveWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LegalSection;
      return this.apiClient.callApi(
        '/api/legal-section/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint for managing legal information in the footer. Supports GET, PUT, and PATCH operations to retrieve or update the legal information. Only one instance of this model exists.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LegalSection}
     */
    legalSectionRetrieve() {
      return this.legalSectionRetrieveWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API endpoint for managing legal information in the footer. Supports GET, PUT, and PATCH operations to retrieve or update the legal information. Only one instance of this model exists.
     * @param {module:model/LegalSectionRequest} legalSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LegalSection} and HTTP response
     */
    legalSectionUpdateWithHttpInfo(legalSectionRequest) {
      let postBody = legalSectionRequest;
      // verify the required parameter 'legalSectionRequest' is set
      if (legalSectionRequest === undefined || legalSectionRequest === null) {
        throw new Error("Missing the required parameter 'legalSectionRequest' when calling legalSectionUpdate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LegalSection;
      return this.apiClient.callApi(
        '/api/legal-section/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint for managing legal information in the footer. Supports GET, PUT, and PATCH operations to retrieve or update the legal information. Only one instance of this model exists.
     * @param {module:model/LegalSectionRequest} legalSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LegalSection}
     */
    legalSectionUpdate(legalSectionRequest) {
      return this.legalSectionUpdateWithHttpInfo(legalSectionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
