/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LocationSection from '../model/LocationSection';
import LocationSectionRequest from '../model/LocationSectionRequest';
import PatchedLocationSectionRequest from '../model/PatchedLocationSectionRequest';

/**
* LocationSection service.
* @module api/LocationSectionApi
* @version 1.0.0
*/
export default class LocationSectionApi {

    /**
    * Constructs a new LocationSectionApi. 
    * @alias module:api/LocationSectionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * API endpoint for managing the Location Section titles. Supports retrieving and updating the primary and secondary titles. Only one instance should exist.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedLocationSectionRequest} [patchedLocationSectionRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LocationSection} and HTTP response
     */
    locationSectionPartialUpdateWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['patchedLocationSectionRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LocationSection;
      return this.apiClient.callApi(
        '/api/location-section/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint for managing the Location Section titles. Supports retrieving and updating the primary and secondary titles. Only one instance should exist.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedLocationSectionRequest} opts.patchedLocationSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LocationSection}
     */
    locationSectionPartialUpdate(opts) {
      return this.locationSectionPartialUpdateWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API endpoint for managing the Location Section titles. Supports retrieving and updating the primary and secondary titles. Only one instance should exist.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LocationSection} and HTTP response
     */
    locationSectionRetrieveWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LocationSection;
      return this.apiClient.callApi(
        '/api/location-section/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint for managing the Location Section titles. Supports retrieving and updating the primary and secondary titles. Only one instance should exist.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LocationSection}
     */
    locationSectionRetrieve() {
      return this.locationSectionRetrieveWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * API endpoint for managing the Location Section titles. Supports retrieving and updating the primary and secondary titles. Only one instance should exist.
     * @param {module:model/LocationSectionRequest} locationSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LocationSection} and HTTP response
     */
    locationSectionUpdateWithHttpInfo(locationSectionRequest) {
      let postBody = locationSectionRequest;
      // verify the required parameter 'locationSectionRequest' is set
      if (locationSectionRequest === undefined || locationSectionRequest === null) {
        throw new Error("Missing the required parameter 'locationSectionRequest' when calling locationSectionUpdate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LocationSection;
      return this.apiClient.callApi(
        '/api/location-section/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * API endpoint for managing the Location Section titles. Supports retrieving and updating the primary and secondary titles. Only one instance should exist.
     * @param {module:model/LocationSectionRequest} locationSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LocationSection}
     */
    locationSectionUpdate(locationSectionRequest) {
      return this.locationSectionUpdateWithHttpInfo(locationSectionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
