/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Operation from '../model/Operation';
import OperationRequest from '../model/OperationRequest';
import PaginatedOperationList from '../model/PaginatedOperationList';
import PatchedOperationRequest from '../model/PatchedOperationRequest';

/**
* Operation service.
* @module api/OperationApi
* @version 1.0.0
*/
export default class OperationApi {

    /**
    * Constructs a new OperationApi. 
    * @alias module:api/OperationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/OperationRequest} operationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Operation} and HTTP response
     */
    operationsCreateWithHttpInfo(operationRequest) {
      let postBody = operationRequest;
      // verify the required parameter 'operationRequest' is set
      if (operationRequest === undefined || operationRequest === null) {
        throw new Error("Missing the required parameter 'operationRequest' when calling operationsCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Operation;
      return this.apiClient.callApi(
        '/api/operations/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/OperationRequest} operationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Operation}
     */
    operationsCreate(operationRequest) {
      return this.operationsCreateWithHttpInfo(operationRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    operationsDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling operationsDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/operations/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    operationsDestroy(id) {
      return this.operationsDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedOperationList} and HTTP response
     */
    operationsListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedOperationList;
      return this.apiClient.callApi(
        '/api/operations/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedOperationList}
     */
    operationsList(opts) {
      return this.operationsListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedOperationRequest} [patchedOperationRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Operation} and HTTP response
     */
    operationsPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedOperationRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling operationsPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Operation;
      return this.apiClient.callApi(
        '/api/operations/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedOperationRequest} opts.patchedOperationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Operation}
     */
    operationsPartialUpdate(id, opts) {
      return this.operationsPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Operation} and HTTP response
     */
    operationsRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling operationsRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Operation;
      return this.apiClient.callApi(
        '/api/operations/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Operation}
     */
    operationsRetrieve(id) {
      return this.operationsRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @param {module:model/OperationRequest} operationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Operation} and HTTP response
     */
    operationsUpdateWithHttpInfo(id, operationRequest) {
      let postBody = operationRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling operationsUpdate");
      }
      // verify the required parameter 'operationRequest' is set
      if (operationRequest === undefined || operationRequest === null) {
        throw new Error("Missing the required parameter 'operationRequest' when calling operationsUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Operation;
      return this.apiClient.callApi(
        '/api/operations/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this operation.
     * @param {module:model/OperationRequest} operationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Operation}
     */
    operationsUpdate(id, operationRequest) {
      return this.operationsUpdateWithHttpInfo(id, operationRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
