/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import OrganisationSection from '../model/OrganisationSection';
import OrganisationSectionRequest from '../model/OrganisationSectionRequest';
import PaginatedOrganisationSectionList from '../model/PaginatedOrganisationSectionList';
import PatchedOrganisationSectionRequest from '../model/PatchedOrganisationSectionRequest';

/**
* OrganisationSection service.
* @module api/OrganisationSectionApi
* @version 1.0.0
*/
export default class OrganisationSectionApi {

    /**
    * Constructs a new OrganisationSectionApi. 
    * @alias module:api/OrganisationSectionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedOrganisationSectionList} and HTTP response
     */
    organisationSectionListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedOrganisationSectionList;
      return this.apiClient.callApi(
        '/api/organisation-section/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedOrganisationSectionList}
     */
    organisationSectionList(opts) {
      return this.organisationSectionListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Number} id A unique integer value identifying this Organisation Section.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedOrganisationSectionRequest} [patchedOrganisationSectionRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OrganisationSection} and HTTP response
     */
    organisationSectionPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedOrganisationSectionRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling organisationSectionPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = OrganisationSection;
      return this.apiClient.callApi(
        '/api/organisation-section/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Number} id A unique integer value identifying this Organisation Section.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedOrganisationSectionRequest} opts.patchedOrganisationSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OrganisationSection}
     */
    organisationSectionPartialUpdate(id, opts) {
      return this.organisationSectionPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Number} id A unique integer value identifying this Organisation Section.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OrganisationSection} and HTTP response
     */
    organisationSectionRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling organisationSectionRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OrganisationSection;
      return this.apiClient.callApi(
        '/api/organisation-section/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Number} id A unique integer value identifying this Organisation Section.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OrganisationSection}
     */
    organisationSectionRetrieve(id) {
      return this.organisationSectionRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Number} id A unique integer value identifying this Organisation Section.
     * @param {module:model/OrganisationSectionRequest} organisationSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OrganisationSection} and HTTP response
     */
    organisationSectionUpdateWithHttpInfo(id, organisationSectionRequest) {
      let postBody = organisationSectionRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling organisationSectionUpdate");
      }
      // verify the required parameter 'organisationSectionRequest' is set
      if (organisationSectionRequest === undefined || organisationSectionRequest === null) {
        throw new Error("Missing the required parameter 'organisationSectionRequest' when calling organisationSectionUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = OrganisationSection;
      return this.apiClient.callApi(
        '/api/organisation-section/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing the organisation section metadata. Supports GET, PUT, and PATCH operations.
     * @param {Number} id A unique integer value identifying this Organisation Section.
     * @param {module:model/OrganisationSectionRequest} organisationSectionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OrganisationSection}
     */
    organisationSectionUpdate(id, organisationSectionRequest) {
      return this.organisationSectionUpdateWithHttpInfo(id, organisationSectionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
