/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PaginatedRegionList from '../model/PaginatedRegionList';
import PatchedRegionRequest from '../model/PatchedRegionRequest';
import Region from '../model/Region';
import RegionRequest from '../model/RegionRequest';

/**
* Region service.
* @module api/RegionApi
* @version 1.0.0
*/
export default class RegionApi {

    /**
    * Constructs a new RegionApi. 
    * @alias module:api/RegionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/RegionRequest} regionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Region} and HTTP response
     */
    regionsCreateWithHttpInfo(regionRequest) {
      let postBody = regionRequest;
      // verify the required parameter 'regionRequest' is set
      if (regionRequest === undefined || regionRequest === null) {
        throw new Error("Missing the required parameter 'regionRequest' when calling regionsCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Region;
      return this.apiClient.callApi(
        '/api/regions/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/RegionRequest} regionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Region}
     */
    regionsCreate(regionRequest) {
      return this.regionsCreateWithHttpInfo(regionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    regionsDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling regionsDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/regions/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    regionsDestroy(id) {
      return this.regionsDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedRegionList} and HTTP response
     */
    regionsListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedRegionList;
      return this.apiClient.callApi(
        '/api/regions/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedRegionList}
     */
    regionsList(opts) {
      return this.regionsListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedRegionRequest} [patchedRegionRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Region} and HTTP response
     */
    regionsPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedRegionRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling regionsPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Region;
      return this.apiClient.callApi(
        '/api/regions/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedRegionRequest} opts.patchedRegionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Region}
     */
    regionsPartialUpdate(id, opts) {
      return this.regionsPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Region} and HTTP response
     */
    regionsRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling regionsRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Region;
      return this.apiClient.callApi(
        '/api/regions/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Region}
     */
    regionsRetrieve(id) {
      return this.regionsRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @param {module:model/RegionRequest} regionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Region} and HTTP response
     */
    regionsUpdateWithHttpInfo(id, regionRequest) {
      let postBody = regionRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling regionsUpdate");
      }
      // verify the required parameter 'regionRequest' is set
      if (regionRequest === undefined || regionRequest === null) {
        throw new Error("Missing the required parameter 'regionRequest' when calling regionsUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Region;
      return this.apiClient.callApi(
        '/api/regions/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this Region.
     * @param {module:model/RegionRequest} regionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Region}
     */
    regionsUpdate(id, regionRequest) {
      return this.regionsUpdateWithHttpInfo(id, regionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
