/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PaginatedSocialMediaList from '../model/PaginatedSocialMediaList';
import PatchedSocialMediaRequest from '../model/PatchedSocialMediaRequest';
import SocialMedia from '../model/SocialMedia';
import SocialMediaRequest from '../model/SocialMediaRequest';

/**
* SocialMedia service.
* @module api/SocialMediaApi
* @version 1.0.0
*/
export default class SocialMediaApi {

    /**
    * Constructs a new SocialMediaApi. 
    * @alias module:api/SocialMediaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {module:model/SocialMediaRequest} socialMediaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SocialMedia} and HTTP response
     */
    socialMediaCreateWithHttpInfo(socialMediaRequest) {
      let postBody = socialMediaRequest;
      // verify the required parameter 'socialMediaRequest' is set
      if (socialMediaRequest === undefined || socialMediaRequest === null) {
        throw new Error("Missing the required parameter 'socialMediaRequest' when calling socialMediaCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = SocialMedia;
      return this.apiClient.callApi(
        '/api/social-media/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {module:model/SocialMediaRequest} socialMediaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SocialMedia}
     */
    socialMediaCreate(socialMediaRequest) {
      return this.socialMediaCreateWithHttpInfo(socialMediaRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    socialMediaDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling socialMediaDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/social-media/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    socialMediaDestroy(id) {
      return this.socialMediaDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedSocialMediaList} and HTTP response
     */
    socialMediaListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedSocialMediaList;
      return this.apiClient.callApi(
        '/api/social-media/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedSocialMediaList}
     */
    socialMediaList(opts) {
      return this.socialMediaListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedSocialMediaRequest} [patchedSocialMediaRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SocialMedia} and HTTP response
     */
    socialMediaPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedSocialMediaRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling socialMediaPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = SocialMedia;
      return this.apiClient.callApi(
        '/api/social-media/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedSocialMediaRequest} opts.patchedSocialMediaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SocialMedia}
     */
    socialMediaPartialUpdate(id, opts) {
      return this.socialMediaPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SocialMedia} and HTTP response
     */
    socialMediaRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling socialMediaRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SocialMedia;
      return this.apiClient.callApi(
        '/api/social-media/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SocialMedia}
     */
    socialMediaRetrieve(id) {
      return this.socialMediaRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @param {module:model/SocialMediaRequest} socialMediaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SocialMedia} and HTTP response
     */
    socialMediaUpdateWithHttpInfo(id, socialMediaRequest) {
      let postBody = socialMediaRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling socialMediaUpdate");
      }
      // verify the required parameter 'socialMediaRequest' is set
      if (socialMediaRequest === undefined || socialMediaRequest === null) {
        throw new Error("Missing the required parameter 'socialMediaRequest' when calling socialMediaUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = SocialMedia;
      return this.apiClient.callApi(
        '/api/social-media/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ViewSet for managing social media links. Provides CRUD operations for social media platforms that appear on the site.  GET: Returns a list of all active social media platforms POST, PUT, PATCH, DELETE: Available to admin users for managing social media links
     * @param {Number} id A unique integer value identifying this Social Media.
     * @param {module:model/SocialMediaRequest} socialMediaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SocialMedia}
     */
    socialMediaUpdate(id, socialMediaRequest) {
      return this.socialMediaUpdateWithHttpInfo(id, socialMediaRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
