/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PaginatedTaskList from '../model/PaginatedTaskList';
import PatchedTaskRequest from '../model/PatchedTaskRequest';
import Task from '../model/Task';
import TaskRequest from '../model/TaskRequest';

/**
* Task service.
* @module api/TaskApi
* @version 1.0.0
*/
export default class TaskApi {

    /**
    * Constructs a new TaskApi. 
    * @alias module:api/TaskApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/TaskRequest} taskRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Task} and HTTP response
     */
    tasksCreateWithHttpInfo(taskRequest) {
      let postBody = taskRequest;
      // verify the required parameter 'taskRequest' is set
      if (taskRequest === undefined || taskRequest === null) {
        throw new Error("Missing the required parameter 'taskRequest' when calling tasksCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/api/tasks/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/TaskRequest} taskRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Task}
     */
    tasksCreate(taskRequest) {
      return this.tasksCreateWithHttpInfo(taskRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    tasksDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasksDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/tasks/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    tasksDestroy(id) {
      return this.tasksDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedTaskList} and HTTP response
     */
    tasksListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedTaskList;
      return this.apiClient.callApi(
        '/api/tasks/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedTaskList}
     */
    tasksList(opts) {
      return this.tasksListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedTaskRequest} [patchedTaskRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Task} and HTTP response
     */
    tasksPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedTaskRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasksPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/api/tasks/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedTaskRequest} opts.patchedTaskRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Task}
     */
    tasksPartialUpdate(id, opts) {
      return this.tasksPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Task} and HTTP response
     */
    tasksRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasksRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/api/tasks/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Task}
     */
    tasksRetrieve(id) {
      return this.tasksRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @param {module:model/TaskRequest} taskRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Task} and HTTP response
     */
    tasksUpdateWithHttpInfo(id, taskRequest) {
      let postBody = taskRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasksUpdate");
      }
      // verify the required parameter 'taskRequest' is set
      if (taskRequest === undefined || taskRequest === null) {
        throw new Error("Missing the required parameter 'taskRequest' when calling tasksUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/api/tasks/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this task.
     * @param {module:model/TaskRequest} taskRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Task}
     */
    tasksUpdate(id, taskRequest) {
      return this.tasksUpdateWithHttpInfo(id, taskRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
