/**
 * Timesheet API
 * API for regions, clients, operations, tasks, timesheets, submissions & approvals
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PaginatedWorkOrderList from '../model/PaginatedWorkOrderList';
import PatchedWorkOrderRequest from '../model/PatchedWorkOrderRequest';
import WorkOrder from '../model/WorkOrder';
import WorkOrderRequest from '../model/WorkOrderRequest';

/**
* WorkOrder service.
* @module api/WorkOrderApi
* @version 1.0.0
*/
export default class WorkOrderApi {

    /**
    * Constructs a new WorkOrderApi. 
    * @alias module:api/WorkOrderApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/WorkOrderRequest} workOrderRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkOrder} and HTTP response
     */
    workordersCreateWithHttpInfo(workOrderRequest) {
      let postBody = workOrderRequest;
      // verify the required parameter 'workOrderRequest' is set
      if (workOrderRequest === undefined || workOrderRequest === null) {
        throw new Error("Missing the required parameter 'workOrderRequest' when calling workordersCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = WorkOrder;
      return this.apiClient.callApi(
        '/api/workorders/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {module:model/WorkOrderRequest} workOrderRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkOrder}
     */
    workordersCreate(workOrderRequest) {
      return this.workordersCreateWithHttpInfo(workOrderRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    workordersDestroyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling workordersDestroy");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/workorders/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    workordersDestroy(id) {
      return this.workordersDestroyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} [ordering] Which field to use when ordering the results.
     * @param {Number} [page] A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedWorkOrderList} and HTTP response
     */
    workordersListWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'ordering': opts['ordering'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedWorkOrderList;
      return this.apiClient.callApi(
        '/api/workorders/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Object} opts Optional parameters
     * @param {String} opts.ordering Which field to use when ordering the results.
     * @param {Number} opts.page A page number within the paginated result set.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedWorkOrderList}
     */
    workordersList(opts) {
      return this.workordersListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedWorkOrderRequest} [patchedWorkOrderRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkOrder} and HTTP response
     */
    workordersPartialUpdateWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['patchedWorkOrderRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling workordersPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = WorkOrder;
      return this.apiClient.callApi(
        '/api/workorders/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @param {Object} opts Optional parameters
     * @param {module:model/PatchedWorkOrderRequest} opts.patchedWorkOrderRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkOrder}
     */
    workordersPartialUpdate(id, opts) {
      return this.workordersPartialUpdateWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkOrder} and HTTP response
     */
    workordersRetrieveWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling workordersRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WorkOrder;
      return this.apiClient.callApi(
        '/api/workorders/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkOrder}
     */
    workordersRetrieve(id) {
      return this.workordersRetrieveWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @param {module:model/WorkOrderRequest} workOrderRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkOrder} and HTTP response
     */
    workordersUpdateWithHttpInfo(id, workOrderRequest) {
      let postBody = workOrderRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling workordersUpdate");
      }
      // verify the required parameter 'workOrderRequest' is set
      if (workOrderRequest === undefined || workOrderRequest === null) {
        throw new Error("Missing the required parameter 'workOrderRequest' when calling workordersUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'cookieAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = WorkOrder;
      return this.apiClient.callApi(
        '/api/workorders/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filters queryset by coordinator's allowed regions using a model->field map. Filtra el queryset por las regiones permitidas del coordinador usando un mapa modelo->campo.
     * @param {Number} id A unique integer value identifying this work order.
     * @param {module:model/WorkOrderRequest} workOrderRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkOrder}
     */
    workordersUpdate(id, workOrderRequest) {
      return this.workordersUpdateWithHttpInfo(id, workOrderRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
